"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfApp = instanceOfApp;
exports.AppFromJSON = AppFromJSON;
exports.AppFromJSONTyped = AppFromJSONTyped;
exports.AppToJSON = AppToJSON;
exports.AppToJSONTyped = AppToJSONTyped;
const AppStatus_1 = require("./AppStatus");
const AppBillingState_1 = require("./AppBillingState");
/**
 * Check if a given object implements the App interface.
 */
function instanceOfApp(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('inUse' in value) || value['inUse'] === undefined)
        return false;
    if (!('billingState' in value) || value['billingState'] === undefined)
        return false;
    if (!('maintenance' in value) || value['maintenance'] === undefined)
        return false;
    if (!('status' in value) || value['status'] === undefined)
        return false;
    if (!('statusMessage' in value) || value['statusMessage'] === undefined)
        return false;
    return true;
}
function AppFromJSON(json) {
    return AppFromJSONTyped(json, false);
}
function AppFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'inUse': json['inUse'],
        'billingState': (0, AppBillingState_1.AppBillingStateFromJSON)(json['billingState']),
        'maintenance': json['maintenance'],
        'status': (0, AppStatus_1.AppStatusFromJSON)(json['status']),
        'statusMessage': json['statusMessage'],
    };
}
function AppToJSON(json) {
    return AppToJSONTyped(json, false);
}
function AppToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'inUse': value['inUse'],
        'billingState': (0, AppBillingState_1.AppBillingStateToJSON)(value['billingState']),
        'maintenance': value['maintenance'],
        'status': (0, AppStatus_1.AppStatusToJSON)(value['status']),
        'statusMessage': value['statusMessage'],
    };
}
