"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppBillingState = void 0;
exports.instanceOfAppBillingState = instanceOfAppBillingState;
exports.AppBillingStateFromJSON = AppBillingStateFromJSON;
exports.AppBillingStateFromJSONTyped = AppBillingStateFromJSONTyped;
exports.AppBillingStateToJSON = AppBillingStateToJSON;
exports.AppBillingStateToJSONTyped = AppBillingStateToJSONTyped;
/**
 *
 * @export
 */
exports.AppBillingState = {
    Free: 'free',
    Active: 'active',
    Cancelled: 'cancelled',
    Indie: 'indie',
    Mini: 'mini'
};
function instanceOfAppBillingState(value) {
    for (const key in exports.AppBillingState) {
        if (Object.prototype.hasOwnProperty.call(exports.AppBillingState, key)) {
            if (exports.AppBillingState[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function AppBillingStateFromJSON(json) {
    return AppBillingStateFromJSONTyped(json, false);
}
function AppBillingStateFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function AppBillingStateToJSON(value) {
    return value;
}
function AppBillingStateToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
