"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.AppLocationSettingStatus = void 0;
exports.instanceOfAppLocationSettingStatus = instanceOfAppLocationSettingStatus;
exports.AppLocationSettingStatusFromJSON = AppLocationSettingStatusFromJSON;
exports.AppLocationSettingStatusFromJSONTyped = AppLocationSettingStatusFromJSONTyped;
exports.AppLocationSettingStatusToJSON = AppLocationSettingStatusToJSON;
exports.AppLocationSettingStatusToJSONTyped = AppLocationSettingStatusToJSONTyped;
/**
 *
 * @export
 */
exports.AppLocationSettingStatus = {
    Pending: 'pending',
    Creating: 'creating',
    Updating: 'updating',
    Deleting: 'deleting',
    Upscaling: 'upscaling',
    Downscaling: 'downscaling',
    Error: 'error',
    Ready: 'ready',
    Waiting: 'waiting',
    Moving: 'moving',
    Cloning: 'cloning'
};
function instanceOfAppLocationSettingStatus(value) {
    for (const key in exports.AppLocationSettingStatus) {
        if (Object.prototype.hasOwnProperty.call(exports.AppLocationSettingStatus, key)) {
            if (exports.AppLocationSettingStatus[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function AppLocationSettingStatusFromJSON(json) {
    return AppLocationSettingStatusFromJSONTyped(json, false);
}
function AppLocationSettingStatusFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function AppLocationSettingStatusToJSON(value) {
    return value;
}
function AppLocationSettingStatusToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
