"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfAppLocationSetting = instanceOfAppLocationSetting;
exports.AppLocationSettingFromJSON = AppLocationSettingFromJSON;
exports.AppLocationSettingFromJSONTyped = AppLocationSettingFromJSONTyped;
exports.AppLocationSettingToJSON = AppLocationSettingToJSON;
exports.AppLocationSettingToJSONTyped = AppLocationSettingToJSONTyped;
const ServerConfig_1 = require("./ServerConfig");
const Placement_1 = require("./Placement");
const AppLocationSettingStatus_1 = require("./AppLocationSettingStatus");
/**
 * Check if a given object implements the AppLocationSetting interface.
 */
function instanceOfAppLocationSetting(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('appId' in value) || value['appId'] === undefined)
        return false;
    if (!('serverConfigId' in value) || value['serverConfigId'] === undefined)
        return false;
    if (!('numInstances' in value) || value['numInstances'] === undefined)
        return false;
    if (!('autoScalerEnabled' in value) || value['autoScalerEnabled'] === undefined)
        return false;
    if (!('status' in value) || value['status'] === undefined)
        return false;
    if (!('statusMessage' in value) || value['statusMessage'] === undefined)
        return false;
    if (!('maintenance' in value) || value['maintenance'] === undefined)
        return false;
    if (!('inUse' in value) || value['inUse'] === undefined)
        return false;
    if (!('placement' in value) || value['placement'] === undefined)
        return false;
    return true;
}
function AppLocationSettingFromJSON(json) {
    return AppLocationSettingFromJSONTyped(json, false);
}
function AppLocationSettingFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'appId': json['appId'],
        'serverConfigId': json['serverConfigId'],
        'numInstances': json['numInstances'],
        'autoScalerEnabled': json['autoScalerEnabled'],
        'autoScalerMin': json['autoScalerMin'] == null ? undefined : json['autoScalerMin'],
        'autoScalerMax': json['autoScalerMax'] == null ? undefined : json['autoScalerMax'],
        'status': (0, AppLocationSettingStatus_1.AppLocationSettingStatusFromJSON)(json['status']),
        'statusMessage': json['statusMessage'],
        'maintenance': json['maintenance'],
        'inUse': json['inUse'],
        'placement': (0, Placement_1.PlacementFromJSON)(json['placement']),
        'serverConfig': json['serverConfig'] == null ? undefined : (0, ServerConfig_1.ServerConfigFromJSON)(json['serverConfig']),
    };
}
function AppLocationSettingToJSON(json) {
    return AppLocationSettingToJSONTyped(json, false);
}
function AppLocationSettingToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'appId': value['appId'],
        'serverConfigId': value['serverConfigId'],
        'numInstances': value['numInstances'],
        'autoScalerEnabled': value['autoScalerEnabled'],
        'autoScalerMin': value['autoScalerMin'],
        'autoScalerMax': value['autoScalerMax'],
        'status': (0, AppLocationSettingStatus_1.AppLocationSettingStatusToJSON)(value['status']),
        'statusMessage': value['statusMessage'],
        'maintenance': value['maintenance'],
        'inUse': value['inUse'],
        'placement': (0, Placement_1.PlacementToJSON)(value['placement']),
        'serverConfig': (0, ServerConfig_1.ServerConfigToJSON)(value['serverConfig']),
    };
}
