"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfBackup = instanceOfBackup;
exports.BackupFromJSON = BackupFromJSON;
exports.BackupFromJSONTyped = BackupFromJSONTyped;
exports.BackupToJSON = BackupToJSON;
exports.BackupToJSONTyped = BackupToJSONTyped;
/**
 * Check if a given object implements the Backup interface.
 */
function instanceOfBackup(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('archiveName' in value) || value['archiveName'] === undefined)
        return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined)
        return false;
    if (!('restoredAt' in value) || value['restoredAt'] === undefined)
        return false;
    return true;
}
function BackupFromJSON(json) {
    return BackupFromJSONTyped(json, false);
}
function BackupFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'archiveName': json['archiveName'],
        'createdAt': (new Date(json['createdAt'])),
        'restoredAt': (json['restoredAt'] == null ? null : new Date(json['restoredAt'])),
    };
}
function BackupToJSON(json) {
    return BackupToJSONTyped(json, false);
}
function BackupToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'archiveName': value['archiveName'],
        'createdAt': value['createdAt'].toISOString(),
        'restoredAt': value['restoredAt'] == null ? value['restoredAt'] : value['restoredAt'].toISOString(),
    };
}
