"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfBackupDownload = instanceOfBackupDownload;
exports.BackupDownloadFromJSON = BackupDownloadFromJSON;
exports.BackupDownloadFromJSONTyped = BackupDownloadFromJSONTyped;
exports.BackupDownloadToJSON = BackupDownloadToJSON;
exports.BackupDownloadToJSONTyped = BackupDownloadToJSONTyped;
/**
 * Check if a given object implements the BackupDownload interface.
 */
function instanceOfBackupDownload(value) {
    if (!('url' in value) || value['url'] === undefined)
        return false;
    if (!('validUntil' in value) || value['validUntil'] === undefined)
        return false;
    return true;
}
function BackupDownloadFromJSON(json) {
    return BackupDownloadFromJSONTyped(json, false);
}
function BackupDownloadFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'url': json['url'],
        'validUntil': (new Date(json['validUntil'])),
    };
}
function BackupDownloadToJSON(json) {
    return BackupDownloadToJSONTyped(json, false);
}
function BackupDownloadToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'url': value['url'],
        'validUntil': value['validUntil'].toISOString(),
    };
}
