"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BinaryStatus = void 0;
exports.instanceOfBinaryStatus = instanceOfBinaryStatus;
exports.BinaryStatusFromJSON = BinaryStatusFromJSON;
exports.BinaryStatusFromJSONTyped = BinaryStatusFromJSONTyped;
exports.BinaryStatusToJSON = BinaryStatusToJSON;
exports.BinaryStatusToJSONTyped = BinaryStatusToJSONTyped;
/**
 *
 * @export
 */
exports.BinaryStatus = {
    Pending: 'pending',
    Building: 'building',
    Deleting: 'deleting',
    Updating: 'updating',
    Waiting: 'waiting',
    Error: 'error',
    Ready: 'ready'
};
function instanceOfBinaryStatus(value) {
    for (const key in exports.BinaryStatus) {
        if (Object.prototype.hasOwnProperty.call(exports.BinaryStatus, key)) {
            if (exports.BinaryStatus[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function BinaryStatusFromJSON(json) {
    return BinaryStatusFromJSONTyped(json, false);
}
function BinaryStatusFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function BinaryStatusToJSON(value) {
    return value;
}
function BinaryStatusToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
