"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BinaryType = void 0;
exports.instanceOfBinaryType = instanceOfBinaryType;
exports.BinaryTypeFromJSON = BinaryTypeFromJSON;
exports.BinaryTypeFromJSONTyped = BinaryTypeFromJSONTyped;
exports.BinaryTypeToJSON = BinaryTypeToJSON;
exports.BinaryTypeToJSONTyped = BinaryTypeToJSONTyped;
/**
 *
 * @export
 */
exports.BinaryType = {
    DockerImage: 'dockerImage',
    Steam: 'steam'
};
function instanceOfBinaryType(value) {
    for (const key in exports.BinaryType) {
        if (Object.prototype.hasOwnProperty.call(exports.BinaryType, key)) {
            if (exports.BinaryType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function BinaryTypeFromJSON(json) {
    return BinaryTypeFromJSONTyped(json, false);
}
function BinaryTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function BinaryTypeToJSON(value) {
    return value;
}
function BinaryTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
