"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfCreateUpdateDockerImage = instanceOfCreateUpdateDockerImage;
exports.CreateUpdateDockerImageFromJSON = CreateUpdateDockerImageFromJSON;
exports.CreateUpdateDockerImageFromJSONTyped = CreateUpdateDockerImageFromJSONTyped;
exports.CreateUpdateDockerImageToJSON = CreateUpdateDockerImageToJSON;
exports.CreateUpdateDockerImageToJSONTyped = CreateUpdateDockerImageToJSONTyped;
/**
 * Check if a given object implements the CreateUpdateDockerImage interface.
 */
function instanceOfCreateUpdateDockerImage(value) {
    if (!('imageName' in value) || value['imageName'] === undefined)
        return false;
    if (!('registryId' in value) || value['registryId'] === undefined)
        return false;
    return true;
}
function CreateUpdateDockerImageFromJSON(json) {
    return CreateUpdateDockerImageFromJSONTyped(json, false);
}
function CreateUpdateDockerImageFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'imageName': json['imageName'],
        'registryId': json['registryId'],
    };
}
function CreateUpdateDockerImageToJSON(json) {
    return CreateUpdateDockerImageToJSONTyped(json, false);
}
function CreateUpdateDockerImageToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'imageName': value['imageName'],
        'registryId': value['registryId'],
    };
}
