"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.DockerRegistryType = void 0;
exports.instanceOfDockerRegistryType = instanceOfDockerRegistryType;
exports.DockerRegistryTypeFromJSON = DockerRegistryTypeFromJSON;
exports.DockerRegistryTypeFromJSONTyped = DockerRegistryTypeFromJSONTyped;
exports.DockerRegistryTypeToJSON = DockerRegistryTypeToJSON;
exports.DockerRegistryTypeToJSONTyped = DockerRegistryTypeToJSONTyped;
/**
 *
 * @export
 */
exports.DockerRegistryType = {
    Default: 'default',
    Gitlab: 'gitlab',
    Github: 'github',
    Custom: 'custom',
    Dockerhub: 'dockerhub',
    Azure: 'azure',
    Awsecr: 'awsecr',
    Other: 'other'
};
function instanceOfDockerRegistryType(value) {
    for (const key in exports.DockerRegistryType) {
        if (Object.prototype.hasOwnProperty.call(exports.DockerRegistryType, key)) {
            if (exports.DockerRegistryType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function DockerRegistryTypeFromJSON(json) {
    return DockerRegistryTypeFromJSONTyped(json, false);
}
function DockerRegistryTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function DockerRegistryTypeToJSON(value) {
    return value;
}
function DockerRegistryTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
