"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EnvironmentVariableType = void 0;
exports.instanceOfEnvironmentVariableType = instanceOfEnvironmentVariableType;
exports.EnvironmentVariableTypeFromJSON = EnvironmentVariableTypeFromJSON;
exports.EnvironmentVariableTypeFromJSONTyped = EnvironmentVariableTypeFromJSONTyped;
exports.EnvironmentVariableTypeToJSON = EnvironmentVariableTypeToJSON;
exports.EnvironmentVariableTypeToJSONTyped = EnvironmentVariableTypeToJSONTyped;
/**
 *
 * @export
 */
exports.EnvironmentVariableType = {
    Static: 'static',
    System: 'system',
    Port: 'port'
};
function instanceOfEnvironmentVariableType(value) {
    for (const key in exports.EnvironmentVariableType) {
        if (Object.prototype.hasOwnProperty.call(exports.EnvironmentVariableType, key)) {
            if (exports.EnvironmentVariableType[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function EnvironmentVariableTypeFromJSON(json) {
    return EnvironmentVariableTypeFromJSONTyped(json, false);
}
function EnvironmentVariableTypeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function EnvironmentVariableTypeToJSON(value) {
    return value;
}
function EnvironmentVariableTypeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
