"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetAppLocationSettings200ResponseMeta = instanceOfGetAppLocationSettings200ResponseMeta;
exports.GetAppLocationSettings200ResponseMetaFromJSON = GetAppLocationSettings200ResponseMetaFromJSON;
exports.GetAppLocationSettings200ResponseMetaFromJSONTyped = GetAppLocationSettings200ResponseMetaFromJSONTyped;
exports.GetAppLocationSettings200ResponseMetaToJSON = GetAppLocationSettings200ResponseMetaToJSON;
exports.GetAppLocationSettings200ResponseMetaToJSONTyped = GetAppLocationSettings200ResponseMetaToJSONTyped;
const GetAppLocationSettings200ResponseMetaLinksInner_1 = require("./GetAppLocationSettings200ResponseMetaLinksInner");
/**
 * Check if a given object implements the GetAppLocationSettings200ResponseMeta interface.
 */
function instanceOfGetAppLocationSettings200ResponseMeta(value) {
    if (!('currentPage' in value) || value['currentPage'] === undefined)
        return false;
    if (!('from' in value) || value['from'] === undefined)
        return false;
    if (!('lastPage' in value) || value['lastPage'] === undefined)
        return false;
    if (!('links' in value) || value['links'] === undefined)
        return false;
    if (!('path' in value) || value['path'] === undefined)
        return false;
    if (!('perPage' in value) || value['perPage'] === undefined)
        return false;
    if (!('to' in value) || value['to'] === undefined)
        return false;
    if (!('total' in value) || value['total'] === undefined)
        return false;
    return true;
}
function GetAppLocationSettings200ResponseMetaFromJSON(json) {
    return GetAppLocationSettings200ResponseMetaFromJSONTyped(json, false);
}
function GetAppLocationSettings200ResponseMetaFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'currentPage': json['current_page'],
        'from': json['from'],
        'lastPage': json['last_page'],
        'links': (json['links'].map(GetAppLocationSettings200ResponseMetaLinksInner_1.GetAppLocationSettings200ResponseMetaLinksInnerFromJSON)),
        'path': json['path'],
        'perPage': json['per_page'],
        'to': json['to'],
        'total': json['total'],
    };
}
function GetAppLocationSettings200ResponseMetaToJSON(json) {
    return GetAppLocationSettings200ResponseMetaToJSONTyped(json, false);
}
function GetAppLocationSettings200ResponseMetaToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'current_page': value['currentPage'],
        'from': value['from'],
        'last_page': value['lastPage'],
        'links': (value['links'].map(GetAppLocationSettings200ResponseMetaLinksInner_1.GetAppLocationSettings200ResponseMetaLinksInnerToJSON)),
        'path': value['path'],
        'per_page': value['perPage'],
        'to': value['to'],
        'total': value['total'],
    };
}
