"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetDockerRegistries200Response = instanceOfGetDockerRegistries200Response;
exports.GetDockerRegistries200ResponseFromJSON = GetDockerRegistries200ResponseFromJSON;
exports.GetDockerRegistries200ResponseFromJSONTyped = GetDockerRegistries200ResponseFromJSONTyped;
exports.GetDockerRegistries200ResponseToJSON = GetDockerRegistries200ResponseToJSON;
exports.GetDockerRegistries200ResponseToJSONTyped = GetDockerRegistries200ResponseToJSONTyped;
const DockerRegistry_1 = require("./DockerRegistry");
const GetAppLocationSettings200ResponseLinks_1 = require("./GetAppLocationSettings200ResponseLinks");
const GetAppLocationSettings200ResponseMeta_1 = require("./GetAppLocationSettings200ResponseMeta");
/**
 * Check if a given object implements the GetDockerRegistries200Response interface.
 */
function instanceOfGetDockerRegistries200Response(value) {
    if (!('data' in value) || value['data'] === undefined)
        return false;
    if (!('links' in value) || value['links'] === undefined)
        return false;
    if (!('meta' in value) || value['meta'] === undefined)
        return false;
    return true;
}
function GetDockerRegistries200ResponseFromJSON(json) {
    return GetDockerRegistries200ResponseFromJSONTyped(json, false);
}
function GetDockerRegistries200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': (json['data'].map(DockerRegistry_1.DockerRegistryFromJSON)),
        'links': (0, GetAppLocationSettings200ResponseLinks_1.GetAppLocationSettings200ResponseLinksFromJSON)(json['links']),
        'meta': (0, GetAppLocationSettings200ResponseMeta_1.GetAppLocationSettings200ResponseMetaFromJSON)(json['meta']),
    };
}
function GetDockerRegistries200ResponseToJSON(json) {
    return GetDockerRegistries200ResponseToJSONTyped(json, false);
}
function GetDockerRegistries200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'data': (value['data'].map(DockerRegistry_1.DockerRegistryToJSON)),
        'links': (0, GetAppLocationSettings200ResponseLinks_1.GetAppLocationSettings200ResponseLinksToJSON)(value['links']),
        'meta': (0, GetAppLocationSettings200ResponseMeta_1.GetAppLocationSettings200ResponseMetaToJSON)(value['meta']),
    };
}
