"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfGetTaggedImages200Response = instanceOfGetTaggedImages200Response;
exports.GetTaggedImages200ResponseFromJSON = GetTaggedImages200ResponseFromJSON;
exports.GetTaggedImages200ResponseFromJSONTyped = GetTaggedImages200ResponseFromJSONTyped;
exports.GetTaggedImages200ResponseToJSON = GetTaggedImages200ResponseToJSON;
exports.GetTaggedImages200ResponseToJSONTyped = GetTaggedImages200ResponseToJSONTyped;
const TaggedImageMetaData_1 = require("./TaggedImageMetaData");
const TaggedImage_1 = require("./TaggedImage");
/**
 * Check if a given object implements the GetTaggedImages200Response interface.
 */
function instanceOfGetTaggedImages200Response(value) {
    if (!('data' in value) || value['data'] === undefined)
        return false;
    if (!('meta' in value) || value['meta'] === undefined)
        return false;
    return true;
}
function GetTaggedImages200ResponseFromJSON(json) {
    return GetTaggedImages200ResponseFromJSONTyped(json, false);
}
function GetTaggedImages200ResponseFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'data': (json['data'].map(TaggedImage_1.TaggedImageFromJSON)),
        'meta': (0, TaggedImageMetaData_1.TaggedImageMetaDataFromJSON)(json['meta']),
    };
}
function GetTaggedImages200ResponseToJSON(json) {
    return GetTaggedImages200ResponseToJSONTyped(json, false);
}
function GetTaggedImages200ResponseToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'data': (value['data'].map(TaggedImage_1.TaggedImageToJSON)),
        'meta': (0, TaggedImageMetaData_1.TaggedImageMetaDataToJSON)(value['meta']),
    };
}
