"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfLocation = instanceOfLocation;
exports.LocationFromJSON = LocationFromJSON;
exports.LocationFromJSONTyped = LocationFromJSONTyped;
exports.LocationToJSON = LocationToJSON;
exports.LocationToJSONTyped = LocationToJSONTyped;
/**
 * Check if a given object implements the Location interface.
 */
function instanceOfLocation(value) {
    if (!('city' in value) || value['city'] === undefined)
        return false;
    if (!('cityDisplay' in value) || value['cityDisplay'] === undefined)
        return false;
    if (!('continent' in value) || value['continent'] === undefined)
        return false;
    if (!('country' in value) || value['country'] === undefined)
        return false;
    if (!('isProtected' in value) || value['isProtected'] === undefined)
        return false;
    return true;
}
function LocationFromJSON(json) {
    return LocationFromJSONTyped(json, false);
}
function LocationFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'city': json['city'],
        'cityDisplay': json['cityDisplay'],
        'continent': json['continent'],
        'country': json['country'],
        'isProtected': json['isProtected'],
    };
}
function LocationToJSON(json) {
    return LocationToJSONTyped(json, false);
}
function LocationToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'city': value['city'],
        'cityDisplay': value['cityDisplay'],
        'continent': value['continent'],
        'country': value['country'],
        'isProtected': value['isProtected'],
    };
}
