"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPlacement = instanceOfPlacement;
exports.PlacementFromJSON = PlacementFromJSON;
exports.PlacementFromJSONTyped = PlacementFromJSONTyped;
exports.PlacementToJSON = PlacementToJSON;
exports.PlacementToJSONTyped = PlacementToJSONTyped;
const Location_1 = require("./Location");
/**
 * Check if a given object implements the Placement interface.
 */
function instanceOfPlacement(value) {
    if (!('constraints' in value) || value['constraints'] === undefined)
        return false;
    return true;
}
function PlacementFromJSON(json) {
    return PlacementFromJSONTyped(json, false);
}
function PlacementFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'constraints': (0, Location_1.LocationFromJSON)(json['constraints']),
    };
}
function PlacementToJSON(json) {
    return PlacementToJSONTyped(json, false);
}
function PlacementToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'constraints': (0, Location_1.LocationToJSON)(value['constraints']),
    };
}
