"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfPort = instanceOfPort;
exports.PortFromJSON = PortFromJSON;
exports.PortFromJSONTyped = PortFromJSONTyped;
exports.PortToJSON = PortToJSON;
exports.PortToJSONTyped = PortToJSONTyped;
const DnsMode_1 = require("./DnsMode");
const Protocol_1 = require("./Protocol");
/**
 * Check if a given object implements the Port interface.
 */
function instanceOfPort(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('protocol' in value) || value['protocol'] === undefined)
        return false;
    if (!('targetPort' in value) || value['targetPort'] === undefined)
        return false;
    if (!('publishedPort' in value) || value['publishedPort'] === undefined)
        return false;
    if (!('dnsMode' in value) || value['dnsMode'] === undefined)
        return false;
    if (!('dnsPrivate' in value) || value['dnsPrivate'] === undefined)
        return false;
    if (!('dnsHttp' in value) || value['dnsHttp'] === undefined)
        return false;
    if (!('dnsHttps' in value) || value['dnsHttps'] === undefined)
        return false;
    return true;
}
function PortFromJSON(json) {
    return PortFromJSONTyped(json, false);
}
function PortFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'protocol': (0, Protocol_1.ProtocolFromJSON)(json['protocol']),
        'targetPort': json['targetPort'],
        'publishedPort': json['publishedPort'],
        'dnsMode': (0, DnsMode_1.DnsModeFromJSON)(json['dnsMode']),
        'dnsPrivate': json['dnsPrivate'],
        'dnsHttp': json['dnsHttp'],
        'dnsHttps': json['dnsHttps'],
    };
}
function PortToJSON(json) {
    return PortToJSONTyped(json, false);
}
function PortToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'protocol': (0, Protocol_1.ProtocolToJSON)(value['protocol']),
        'targetPort': value['targetPort'],
        'publishedPort': value['publishedPort'],
        'dnsMode': (0, DnsMode_1.DnsModeToJSON)(value['dnsMode']),
        'dnsPrivate': value['dnsPrivate'],
        'dnsHttp': value['dnsHttp'],
        'dnsHttps': value['dnsHttps'],
    };
}
