"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfResourcePackage = instanceOfResourcePackage;
exports.ResourcePackageFromJSON = ResourcePackageFromJSON;
exports.ResourcePackageFromJSONTyped = ResourcePackageFromJSONTyped;
exports.ResourcePackageToJSON = ResourcePackageToJSON;
exports.ResourcePackageToJSONTyped = ResourcePackageToJSONTyped;
const ResourcePackageType_1 = require("./ResourcePackageType");
/**
 * Check if a given object implements the ResourcePackage interface.
 */
function instanceOfResourcePackage(value) {
    if (!('id' in value) || value['id'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('slug' in value) || value['slug'] === undefined)
        return false;
    if (!('type' in value) || value['type'] === undefined)
        return false;
    if (!('cpuLimit' in value) || value['cpuLimit'] === undefined)
        return false;
    if (!('memoryLimitBytes' in value) || value['memoryLimitBytes'] === undefined)
        return false;
    if (!('memoryLimitMiB' in value) || value['memoryLimitMiB'] === undefined)
        return false;
    if (!('memoryLimitFileSizeString' in value) || value['memoryLimitFileSizeString'] === undefined)
        return false;
    return true;
}
function ResourcePackageFromJSON(json) {
    return ResourcePackageFromJSONTyped(json, false);
}
function ResourcePackageFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'id': json['id'],
        'name': json['name'],
        'slug': json['slug'],
        'type': (0, ResourcePackageType_1.ResourcePackageTypeFromJSON)(json['type']),
        'cpuLimit': json['cpuLimit'],
        'memoryLimitBytes': json['memoryLimitBytes'],
        'memoryLimitMiB': json['memoryLimitMiB'],
        'memoryLimitFileSizeString': json['memoryLimitFileSizeString'],
    };
}
function ResourcePackageToJSON(json) {
    return ResourcePackageToJSONTyped(json, false);
}
function ResourcePackageToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'type': (0, ResourcePackageType_1.ResourcePackageTypeToJSON)(value['type']),
        'cpuLimit': value['cpuLimit'],
        'memoryLimitBytes': value['memoryLimitBytes'],
        'memoryLimitMiB': value['memoryLimitMiB'],
        'memoryLimitFileSizeString': value['memoryLimitFileSizeString'],
    };
}
