"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfSteamLauncher = instanceOfSteamLauncher;
exports.SteamLauncherFromJSON = SteamLauncherFromJSON;
exports.SteamLauncherFromJSONTyped = SteamLauncherFromJSONTyped;
exports.SteamLauncherToJSON = SteamLauncherToJSON;
exports.SteamLauncherToJSONTyped = SteamLauncherToJSONTyped;
/**
 * Check if a given object implements the SteamLauncher interface.
 */
function instanceOfSteamLauncher(value) {
    if (!('executable' in value) || value['executable'] === undefined)
        return false;
    if (!('arguments' in value) || value['arguments'] === undefined)
        return false;
    if (!('osarch' in value) || value['osarch'] === undefined)
        return false;
    if (!('oslist' in value) || value['oslist'] === undefined)
        return false;
    if (!('realm' in value) || value['realm'] === undefined)
        return false;
    if (!('betakey' in value) || value['betakey'] === undefined)
        return false;
    if (!('description' in value) || value['description'] === undefined)
        return false;
    return true;
}
function SteamLauncherFromJSON(json) {
    return SteamLauncherFromJSONTyped(json, false);
}
function SteamLauncherFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'executable': json['executable'],
        'arguments': json['arguments'],
        'osarch': json['osarch'],
        'oslist': json['oslist'],
        'realm': json['realm'],
        'betakey': json['betakey'],
        'description': json['description'],
    };
}
function SteamLauncherToJSON(json) {
    return SteamLauncherToJSONTyped(json, false);
}
function SteamLauncherToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'executable': value['executable'],
        'arguments': value['arguments'],
        'osarch': value['osarch'],
        'oslist': value['oslist'],
        'realm': value['realm'],
        'betakey': value['betakey'],
        'description': value['description'],
    };
}
