"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfStoreServerConfigRequest = instanceOfStoreServerConfigRequest;
exports.StoreServerConfigRequestFromJSON = StoreServerConfigRequestFromJSON;
exports.StoreServerConfigRequestFromJSONTyped = StoreServerConfigRequestFromJSONTyped;
exports.StoreServerConfigRequestToJSON = StoreServerConfigRequestToJSON;
exports.StoreServerConfigRequestToJSONTyped = StoreServerConfigRequestToJSONTyped;
const ConfigFile_1 = require("./ConfigFile");
const Mount_1 = require("./Mount");
const PortDefinitionRequest_1 = require("./PortDefinitionRequest");
const RestartPolicy_1 = require("./RestartPolicy");
const SecretFile_1 = require("./SecretFile");
const EnvironmentVariableDefinition_1 = require("./EnvironmentVariableDefinition");
/**
 * Check if a given object implements the StoreServerConfigRequest interface.
 */
function instanceOfStoreServerConfigRequest(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('binaryId' in value) || value['binaryId'] === undefined)
        return false;
    if (!('resourcePackageSlug' in value) || value['resourcePackageSlug'] === undefined)
        return false;
    return true;
}
function StoreServerConfigRequestFromJSON(json) {
    return StoreServerConfigRequestFromJSONTyped(json, false);
}
function StoreServerConfigRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'args': json['args'] == null ? undefined : json['args'],
        'command': json['command'] == null ? undefined : json['command'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'binaryId': json['binaryId'],
        'resourcePackageSlug': json['resourcePackageSlug'],
        'dnsServiceEnabled': json['dnsServiceEnabled'] == null ? undefined : json['dnsServiceEnabled'],
        'configFiles': json['configFiles'] == null ? undefined : (json['configFiles'].map(ConfigFile_1.ConfigFileFromJSON)),
        'secretFiles': json['secretFiles'] == null ? undefined : (json['secretFiles'].map(SecretFile_1.SecretFileFromJSON)),
        'restartPolicy': json['restartPolicy'] == null ? undefined : (0, RestartPolicy_1.RestartPolicyFromJSON)(json['restartPolicy']),
        'env': json['env'] == null ? undefined : (json['env'].map(EnvironmentVariableDefinition_1.EnvironmentVariableDefinitionFromJSON)),
        'mounts': json['mounts'] == null ? undefined : (json['mounts'].map(Mount_1.MountFromJSON)),
        'ports': json['ports'] == null ? undefined : (json['ports'].map(PortDefinitionRequest_1.PortDefinitionRequestFromJSON)),
    };
}
function StoreServerConfigRequestToJSON(json) {
    return StoreServerConfigRequestToJSONTyped(json, false);
}
function StoreServerConfigRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'args': value['args'],
        'command': value['command'],
        'notes': value['notes'],
        'binaryId': value['binaryId'],
        'resourcePackageSlug': value['resourcePackageSlug'],
        'dnsServiceEnabled': value['dnsServiceEnabled'],
        'configFiles': value['configFiles'] == null ? undefined : (value['configFiles'].map(ConfigFile_1.ConfigFileToJSON)),
        'secretFiles': value['secretFiles'] == null ? undefined : (value['secretFiles'].map(SecretFile_1.SecretFileToJSON)),
        'restartPolicy': (0, RestartPolicy_1.RestartPolicyToJSON)(value['restartPolicy']),
        'env': value['env'] == null ? undefined : (value['env'].map(EnvironmentVariableDefinition_1.EnvironmentVariableDefinitionToJSON)),
        'mounts': value['mounts'] == null ? undefined : (value['mounts'].map(Mount_1.MountToJSON)),
        'ports': value['ports'] == null ? undefined : (value['ports'].map(PortDefinitionRequest_1.PortDefinitionRequestToJSON)),
    };
}
