"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfStoreMinecraftTemplateRequest = instanceOfStoreMinecraftTemplateRequest;
exports.StoreMinecraftTemplateRequestFromJSON = StoreMinecraftTemplateRequestFromJSON;
exports.StoreMinecraftTemplateRequestFromJSONTyped = StoreMinecraftTemplateRequestFromJSONTyped;
exports.StoreMinecraftTemplateRequestToJSON = StoreMinecraftTemplateRequestToJSON;
exports.StoreMinecraftTemplateRequestToJSONTyped = StoreMinecraftTemplateRequestToJSONTyped;
const CreateUpdatePlacement_1 = require("./CreateUpdatePlacement");
/**
 * Check if a given object implements the StoreMinecraftTemplateRequest interface.
 */
function instanceOfStoreMinecraftTemplateRequest(value) {
    return true;
}
function StoreMinecraftTemplateRequestFromJSON(json) {
    return StoreMinecraftTemplateRequestFromJSONTyped(json, false);
}
function StoreMinecraftTemplateRequestFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'appName': json['appName'] == null ? undefined : json['appName'],
        'resourcePackageSlug': json['resourcePackageSlug'] == null ? undefined : json['resourcePackageSlug'],
        'placement': json['placement'] == null ? undefined : (0, CreateUpdatePlacement_1.CreateUpdatePlacementFromJSON)(json['placement']),
        'password': json['password'] == null ? undefined : json['password'],
    };
}
function StoreMinecraftTemplateRequestToJSON(json) {
    return StoreMinecraftTemplateRequestToJSONTyped(json, false);
}
function StoreMinecraftTemplateRequestToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'appName': value['appName'],
        'resourcePackageSlug': value['resourcePackageSlug'],
        'placement': (0, CreateUpdatePlacement_1.CreateUpdatePlacementToJSON)(value['placement']),
        'password': value['password'],
    };
}
