"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfTaggedImage = instanceOfTaggedImage;
exports.TaggedImageFromJSON = TaggedImageFromJSON;
exports.TaggedImageFromJSONTyped = TaggedImageFromJSONTyped;
exports.TaggedImageToJSON = TaggedImageToJSON;
exports.TaggedImageToJSONTyped = TaggedImageToJSONTyped;
/**
 * Check if a given object implements the TaggedImage interface.
 */
function instanceOfTaggedImage(value) {
    if (!('name' in value) || value['name'] === undefined)
        return false;
    if (!('tag' in value) || value['tag'] === undefined)
        return false;
    if (!('repository' in value) || value['repository'] === undefined)
        return false;
    if (!('location' in value) || value['location'] === undefined)
        return false;
    return true;
}
function TaggedImageFromJSON(json) {
    return TaggedImageFromJSONTyped(json, false);
}
function TaggedImageFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'name': json['name'],
        'tag': json['tag'],
        'repository': json['repository'],
        'location': json['location'],
    };
}
function TaggedImageToJSON(json) {
    return TaggedImageToJSONTyped(json, false);
}
function TaggedImageToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'name': value['name'],
        'tag': value['tag'],
        'repository': value['repository'],
        'location': value['location'],
    };
}
