"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.WalletScope = void 0;
exports.instanceOfWalletScope = instanceOfWalletScope;
exports.WalletScopeFromJSON = WalletScopeFromJSON;
exports.WalletScopeFromJSONTyped = WalletScopeFromJSONTyped;
exports.WalletScopeToJSON = WalletScopeToJSON;
exports.WalletScopeToJSONTyped = WalletScopeToJSONTyped;
/**
 *
 * @export
 */
exports.WalletScope = {
    User: 'user',
    App: 'app'
};
function instanceOfWalletScope(value) {
    for (const key in exports.WalletScope) {
        if (Object.prototype.hasOwnProperty.call(exports.WalletScope, key)) {
            if (exports.WalletScope[key] === value) {
                return true;
            }
        }
    }
    return false;
}
function WalletScopeFromJSON(json) {
    return WalletScopeFromJSONTyped(json, false);
}
function WalletScopeFromJSONTyped(json, ignoreDiscriminator) {
    return json;
}
function WalletScopeToJSON(value) {
    return value;
}
function WalletScopeToJSONTyped(value, ignoreDiscriminator) {
    return value;
}
