"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.instanceOfWalletCurrency = instanceOfWalletCurrency;
exports.WalletCurrencyFromJSON = WalletCurrencyFromJSON;
exports.WalletCurrencyFromJSONTyped = WalletCurrencyFromJSONTyped;
exports.WalletCurrencyToJSON = WalletCurrencyToJSON;
exports.WalletCurrencyToJSONTyped = WalletCurrencyToJSONTyped;
/**
 * Check if a given object implements the WalletCurrency interface.
 */
function instanceOfWalletCurrency(value) {
    if (!('code' in value) || value['code'] === undefined)
        return false;
    if (!('name' in value) || value['name'] === undefined)
        return false;
    return true;
}
function WalletCurrencyFromJSON(json) {
    return WalletCurrencyFromJSONTyped(json, false);
}
function WalletCurrencyFromJSONTyped(json, ignoreDiscriminator) {
    if (json == null) {
        return json;
    }
    return {
        'code': json['code'],
        'name': json['name'],
    };
}
function WalletCurrencyToJSON(json) {
    return WalletCurrencyToJSONTyped(json, false);
}
function WalletCurrencyToJSONTyped(value, ignoreDiscriminator = false) {
    if (value == null) {
        return value;
    }
    return {
        'code': value['code'],
        'name': value['name'],
    };
}
