/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  App,
  GetAppWallets200Response,
  GetApps200Response,
  GetAuthTokenViaFsid403Response,
  InlineObject,
  PatchAppMetadataRequest,
  SetAppMetadataRequest,
  StoreAppRequest,
  UpdateAppLocationSetting402Response,
  UpdateAppRequest,
} from '../models/index';
import {
    AppFromJSON,
    AppToJSON,
    GetAppWallets200ResponseFromJSON,
    GetAppWallets200ResponseToJSON,
    GetApps200ResponseFromJSON,
    GetApps200ResponseToJSON,
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    PatchAppMetadataRequestFromJSON,
    PatchAppMetadataRequestToJSON,
    SetAppMetadataRequestFromJSON,
    SetAppMetadataRequestToJSON,
    StoreAppRequestFromJSON,
    StoreAppRequestToJSON,
    UpdateAppLocationSetting402ResponseFromJSON,
    UpdateAppLocationSetting402ResponseToJSON,
    UpdateAppRequestFromJSON,
    UpdateAppRequestToJSON,
} from '../models/index';

export interface AppApiAppsMetadataDeleteAllRequest {
    app: number;
}

export interface AppApiAppsMetadataDeleteKeysRequest {
    app: number;
    metadata: Array<string>;
}

export interface AppApiAppsMetadataSetRequest {
    app: number;
    setAppMetadataRequest?: SetAppMetadataRequest;
}

export interface AppApiAppsMetadataUpdateRequest {
    app: number;
    patchAppMetadataRequest?: PatchAppMetadataRequest;
}

export interface AppApiCreateAppRequest {
    storeAppRequest: StoreAppRequest;
}

export interface AppApiDeleteAppRequest {
    app: number;
}

export interface AppApiGetAppByIdRequest {
    app: number;
}

export interface AppApiGetAppWalletsRequest {
    app: number;
    perPage?: number;
    page?: number;
    sort?: Array<GetAppWalletsSortEnum>;
    filterId?: number;
    filterBalance?: number;
}

export interface AppApiGetAppsRequest {
    perPage?: number;
    page?: number;
    sort?: Array<GetAppsSortEnum>;
    filterId?: number;
    filterName?: string;
    filterNamePartial?: string;
    filterInUse?: boolean;
    filterMetadata?: string;
}

export interface AppApiStartServersForAppRequest {
    app: number;
}

export interface AppApiStopServersForAppRequest {
    app: number;
}

export interface AppApiUpdateAppByIdRequest {
    app: number;
    updateAppRequest: UpdateAppRequest;
}

/**
 * 
 */
export class AppApi extends runtime.BaseAPI {

    /**
     * Delete all metadata
     */
    async appsMetadataDeleteAllRaw(requestParameters: AppApiAppsMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling appsMetadataDeleteAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/metadata`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Delete all metadata
     */
    async appsMetadataDeleteAll(requestParameters: AppApiAppsMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.appsMetadataDeleteAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete metadata keys
     */
    async appsMetadataDeleteKeysRaw(requestParameters: AppApiAppsMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling appsMetadataDeleteKeys().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling appsMetadataDeleteKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata[]'] = requestParameters['metadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/metadata/keys`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Delete metadata keys
     */
    async appsMetadataDeleteKeys(requestParameters: AppApiAppsMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.appsMetadataDeleteKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the entire metadata.
     * Set metadata
     */
    async appsMetadataSetRaw(requestParameters: AppApiAppsMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling appsMetadataSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/apps/{app}/metadata`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetAppMetadataRequestToJSON(requestParameters['setAppMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Replaces the entire metadata.
     * Set metadata
     */
    async appsMetadataSet(requestParameters: AppApiAppsMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.appsMetadataSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting other metadata.
     * Update metadata
     */
    async appsMetadataUpdateRaw(requestParameters: AppApiAppsMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling appsMetadataUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/apps/{app}/metadata`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchAppMetadataRequestToJSON(requestParameters['patchAppMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting other metadata.
     * Update metadata
     */
    async appsMetadataUpdate(requestParameters: AppApiAppsMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.appsMetadataUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create an app
     */
    async createAppRaw(requestParameters: AppApiCreateAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['storeAppRequest'] == null) {
            throw new runtime.RequiredError(
                'storeAppRequest',
                'Required parameter "storeAppRequest" was null or undefined when calling createApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/apps`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreAppRequestToJSON(requestParameters['storeAppRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Create an app
     */
    async createApp(requestParameters: AppApiCreateAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.createAppRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific app
     */
    async deleteAppRaw(requestParameters: AppApiDeleteAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling deleteApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specific app
     */
    async deleteApp(requestParameters: AppApiDeleteAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteAppRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all unused apps
     */
    async deleteUnusedAppsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/unused`;

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete all unused apps
     */
    async deleteUnusedApps(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUnusedAppsRaw(initOverrides);
    }

    /**
     * Show a specific app
     */
    async getAppByIdRaw(requestParameters: AppApiGetAppByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getAppById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Show a specific app
     */
    async getAppById(requestParameters: AppApiGetAppByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.getAppByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show all wallets for a specific app
     */
    async getAppWalletsRaw(requestParameters: AppApiGetAppWalletsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetAppWallets200Response>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getAppWallets().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterBalance'] != null) {
            queryParameters['filter[balance]'] = requestParameters['filterBalance'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/wallets`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetAppWallets200ResponseFromJSON(jsonValue));
    }

    /**
     * Show all wallets for a specific app
     */
    async getAppWallets(requestParameters: AppApiGetAppWalletsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetAppWallets200Response> {
        const response = await this.getAppWalletsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show all apps
     */
    async getAppsRaw(requestParameters: AppApiGetAppsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetApps200Response>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }

        if (requestParameters['filterInUse'] != null) {
            queryParameters['filter[inUse]'] = requestParameters['filterInUse'];
        }

        if (requestParameters['filterMetadata'] != null) {
            queryParameters['filter[metadata]'] = requestParameters['filterMetadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetApps200ResponseFromJSON(jsonValue));
    }

    /**
     * Show all apps
     */
    async getApps(requestParameters: AppApiGetAppsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetApps200Response> {
        const response = await this.getAppsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start all services related to a specific app
     */
    async startServersForAppRaw(requestParameters: AppApiStartServersForAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling startServersForApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services/start`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start all services related to a specific app
     */
    async startServersForApp(requestParameters: AppApiStartServersForAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startServersForAppRaw(requestParameters, initOverrides);
    }

    /**
     * Stop all services related to a specific app
     */
    async stopServersForAppRaw(requestParameters: AppApiStopServersForAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling stopServersForApp().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services/stop`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop all services related to a specific app
     */
    async stopServersForApp(requestParameters: AppApiStopServersForAppRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.stopServersForAppRaw(requestParameters, initOverrides);
    }

    /**
     * Update a specific app
     */
    async updateAppByIdRaw(requestParameters: AppApiUpdateAppByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<App>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling updateAppById().'
            );
        }

        if (requestParameters['updateAppRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAppRequest',
                'Required parameter "updateAppRequest" was null or undefined when calling updateAppById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/apps/{app}`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAppRequestToJSON(requestParameters['updateAppRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AppFromJSON(jsonValue));
    }

    /**
     * Update a specific app
     */
    async updateAppById(requestParameters: AppApiUpdateAppByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<App> {
        const response = await this.updateAppByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetAppWalletsSortEnum = {
    Id: '-id',
    Id2: 'id',
    Balance: '-balance',
    Balance2: 'balance'
} as const;
export type GetAppWalletsSortEnum = typeof GetAppWalletsSortEnum[keyof typeof GetAppWalletsSortEnum];
/**
 * @export
 */
export const GetAppsSortEnum = {
    Id: '-id',
    Id2: 'id',
    Name: '-name',
    Name2: 'name',
    InUse: '-inUse',
    InUse2: 'inUse'
} as const;
export type GetAppsSortEnum = typeof GetAppsSortEnum[keyof typeof GetAppsSortEnum];
