/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Auth,
  AuthFsidRequest,
  AuthRequest,
  GetAuthTokenViaFsid403Response,
  InlineObject,
} from '../models/index';
import {
    AuthFromJSON,
    AuthToJSON,
    AuthFsidRequestFromJSON,
    AuthFsidRequestToJSON,
    AuthRequestFromJSON,
    AuthRequestToJSON,
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/index';

export interface AuthApiGetAuthTokenRequest {
    authRequest: AuthRequest;
}

export interface AuthApiGetAuthTokenViaFsidRequest {
    authFsidRequest: AuthFsidRequest;
}

/**
 * 
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     * Authenticates the user based on the user\'s email, password, and session ID. If the user is authenticated successfully, it returns the user\'s token.  The token is non-expiring and must be used as a Bearer token in subsequent requests.
     * Get token
     */
    async getAuthTokenRaw(requestParameters: AuthApiGetAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Auth>> {
        if (requestParameters['authRequest'] == null) {
            throw new runtime.RequiredError(
                'authRequest',
                'Required parameter "authRequest" was null or undefined when calling getAuthToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/token`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthRequestToJSON(requestParameters['authRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthFromJSON(jsonValue));
    }

    /**
     * Authenticates the user based on the user\'s email, password, and session ID. If the user is authenticated successfully, it returns the user\'s token.  The token is non-expiring and must be used as a Bearer token in subsequent requests.
     * Get token
     */
    async getAuthToken(requestParameters: AuthApiGetAuthTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Auth> {
        const response = await this.getAuthTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Authenticates the user based on the Fusion Session ID (fsid). If the user is authenticated successfully, it returns the user\'s token.  The token is non-expiring and must be used as a Bearer token in subsequent requests.
     * Get token via fsid
     */
    async getAuthTokenViaFsidRaw(requestParameters: AuthApiGetAuthTokenViaFsidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Auth>> {
        if (requestParameters['authFsidRequest'] == null) {
            throw new runtime.RequiredError(
                'authFsidRequest',
                'Required parameter "authFsidRequest" was null or undefined when calling getAuthTokenViaFsid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/auth/token/fsid`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthFsidRequestToJSON(requestParameters['authFsidRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthFromJSON(jsonValue));
    }

    /**
     * Authenticates the user based on the Fusion Session ID (fsid). If the user is authenticated successfully, it returns the user\'s token.  The token is non-expiring and must be used as a Bearer token in subsequent requests.
     * Get token via fsid
     */
    async getAuthTokenViaFsid(requestParameters: AuthApiGetAuthTokenViaFsidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Auth> {
        const response = await this.getAuthTokenViaFsidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh token
     */
    async refreshAuthTokenRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Auth>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/auth/token`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthFromJSON(jsonValue));
    }

    /**
     * Refresh token
     */
    async refreshAuthToken(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Auth> {
        const response = await this.refreshAuthTokenRaw(initOverrides);
        return await response.value();
    }

}
