/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Binary,
  GetBinaries200Response,
  InlineObject,
  InlineObject1,
  StoreBinaryRequest,
  UpdateAppLocationSetting402Response,
  UpdateBinaryRequest,
} from '../models/index';
import {
    BinaryFromJSON,
    BinaryToJSON,
    GetBinaries200ResponseFromJSON,
    GetBinaries200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    StoreBinaryRequestFromJSON,
    StoreBinaryRequestToJSON,
    UpdateAppLocationSetting402ResponseFromJSON,
    UpdateAppLocationSetting402ResponseToJSON,
    UpdateBinaryRequestFromJSON,
    UpdateBinaryRequestToJSON,
} from '../models/index';

export interface CreateBinaryRequest {
    app: number;
    storeBinaryRequest: StoreBinaryRequest;
}

export interface DeleteBinaryRequest {
    binary: number;
}

export interface DeleteUnusedBinariesRequest {
    app: number;
}

export interface GetBinariesRequest {
    app: number;
    perPage?: number;
    page?: number;
    sort?: Array<string>;
    filterName?: string;
    filterNamePartial?: string;
    filterVersion?: string;
    filterType?: string;
    filterOs?: string;
    filterMaintenance?: boolean;
    filterStatus?: string;
    filterInUse?: boolean;
}

export interface GetBinaryByIdRequest {
    binary: number;
}

export interface RefreshBinaryRequest {
    binary: number;
}

export interface StartServersForBinaryRequest {
    binary: number;
}

export interface StopServersForBinaryRequest {
    binary: number;
}

export interface UpdateBinaryOperationRequest {
    binary: number;
    updateBinaryRequest: UpdateBinaryRequest;
}

/**
 * 
 */
export class BinaryApi extends runtime.BaseAPI {

    /**
     * Create a binary and the related entity
     */
    async createBinaryRaw(requestParameters: CreateBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Binary>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling createBinary().'
            );
        }

        if (requestParameters['storeBinaryRequest'] == null) {
            throw new runtime.RequiredError(
                'storeBinaryRequest',
                'Required parameter "storeBinaryRequest" was null or undefined when calling createBinary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/apps/{app}/binaries`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreBinaryRequestToJSON(requestParameters['storeBinaryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BinaryFromJSON(jsonValue));
    }

    /**
     * Create a binary and the related entity
     */
    async createBinary(requestParameters: CreateBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Binary> {
        const response = await this.createBinaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specified binary
     */
    async deleteBinaryRaw(requestParameters: DeleteBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['binary'] == null) {
            throw new runtime.RequiredError(
                'binary',
                'Required parameter "binary" was null or undefined when calling deleteBinary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/{binary}`;
        urlPath = urlPath.replace(`{${"binary"}}`, encodeURIComponent(String(requestParameters['binary'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specified binary
     */
    async deleteBinary(requestParameters: DeleteBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBinaryRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all unused binaries
     */
    async deleteUnusedBinariesRaw(requestParameters: DeleteUnusedBinariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling deleteUnusedBinaries().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/binaries/unused`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete all unused binaries
     */
    async deleteUnusedBinaries(requestParameters: DeleteUnusedBinariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteUnusedBinariesRaw(requestParameters, initOverrides);
    }

    /**
     * Show all binaries
     */
    async getBinariesRaw(requestParameters: GetBinariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBinaries200Response>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getBinaries().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }

        if (requestParameters['filterVersion'] != null) {
            queryParameters['filter[version]'] = requestParameters['filterVersion'];
        }

        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }

        if (requestParameters['filterOs'] != null) {
            queryParameters['filter[os]'] = requestParameters['filterOs'];
        }

        if (requestParameters['filterMaintenance'] != null) {
            queryParameters['filter[maintenance]'] = requestParameters['filterMaintenance'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterInUse'] != null) {
            queryParameters['filter[inUse]'] = requestParameters['filterInUse'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/binaries`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBinaries200ResponseFromJSON(jsonValue));
    }

    /**
     * Show all binaries
     */
    async getBinaries(requestParameters: GetBinariesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBinaries200Response> {
        const response = await this.getBinariesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show a specific binary
     */
    async getBinaryByIdRaw(requestParameters: GetBinaryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Binary>> {
        if (requestParameters['binary'] == null) {
            throw new runtime.RequiredError(
                'binary',
                'Required parameter "binary" was null or undefined when calling getBinaryById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/{binary}`;
        urlPath = urlPath.replace(`{${"binary"}}`, encodeURIComponent(String(requestParameters['binary'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BinaryFromJSON(jsonValue));
    }

    /**
     * Show a specific binary
     */
    async getBinaryById(requestParameters: GetBinaryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Binary> {
        const response = await this.getBinaryByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh a binary and the related entity
     */
    async refreshBinaryRaw(requestParameters: RefreshBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Binary>> {
        if (requestParameters['binary'] == null) {
            throw new runtime.RequiredError(
                'binary',
                'Required parameter "binary" was null or undefined when calling refreshBinary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/{binary}/refresh`;
        urlPath = urlPath.replace(`{${"binary"}}`, encodeURIComponent(String(requestParameters['binary'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BinaryFromJSON(jsonValue));
    }

    /**
     * Refresh a binary and the related entity
     */
    async refreshBinary(requestParameters: RefreshBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Binary> {
        const response = await this.refreshBinaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Start all services related to a specific binary
     */
    async startServersForBinaryRaw(requestParameters: StartServersForBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['binary'] == null) {
            throw new runtime.RequiredError(
                'binary',
                'Required parameter "binary" was null or undefined when calling startServersForBinary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/{binary}/services/start`;
        urlPath = urlPath.replace(`{${"binary"}}`, encodeURIComponent(String(requestParameters['binary'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start all services related to a specific binary
     */
    async startServersForBinary(requestParameters: StartServersForBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startServersForBinaryRaw(requestParameters, initOverrides);
    }

    /**
     * Stop all services related to a specific binary
     */
    async stopServersForBinaryRaw(requestParameters: StopServersForBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['binary'] == null) {
            throw new runtime.RequiredError(
                'binary',
                'Required parameter "binary" was null or undefined when calling stopServersForBinary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/{binary}/services/stop`;
        urlPath = urlPath.replace(`{${"binary"}}`, encodeURIComponent(String(requestParameters['binary'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop all services related to a specific binary
     */
    async stopServersForBinary(requestParameters: StopServersForBinaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.stopServersForBinaryRaw(requestParameters, initOverrides);
    }

    /**
     * Update a binary and the related entity
     */
    async updateBinaryRaw(requestParameters: UpdateBinaryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Binary>> {
        if (requestParameters['binary'] == null) {
            throw new runtime.RequiredError(
                'binary',
                'Required parameter "binary" was null or undefined when calling updateBinary().'
            );
        }

        if (requestParameters['updateBinaryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateBinaryRequest',
                'Required parameter "updateBinaryRequest" was null or undefined when calling updateBinary().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/binaries/{binary}`;
        urlPath = urlPath.replace(`{${"binary"}}`, encodeURIComponent(String(requestParameters['binary'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateBinaryRequestToJSON(requestParameters['updateBinaryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BinaryFromJSON(jsonValue));
    }

    /**
     * Update a binary and the related entity
     */
    async updateBinary(requestParameters: UpdateBinaryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Binary> {
        const response = await this.updateBinaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
