/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Backup,
  BackupDownload,
  CreateBackupDockerServiceRequest,
  DockerServiceDnsReachable,
  GetAuthTokenViaFsid403Response,
  GetBackups200Response,
  GetServers200Response,
  InlineObject,
  PatchMetadataRequest,
  Server,
  ServiceLogs,
  SetMetadataRequest,
  UpdateAppLocationSetting402Response,
} from '../models/index';
import {
    BackupFromJSON,
    BackupToJSON,
    BackupDownloadFromJSON,
    BackupDownloadToJSON,
    CreateBackupDockerServiceRequestFromJSON,
    CreateBackupDockerServiceRequestToJSON,
    DockerServiceDnsReachableFromJSON,
    DockerServiceDnsReachableToJSON,
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    GetBackups200ResponseFromJSON,
    GetBackups200ResponseToJSON,
    GetServers200ResponseFromJSON,
    GetServers200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    PatchMetadataRequestFromJSON,
    PatchMetadataRequestToJSON,
    ServerFromJSON,
    ServerToJSON,
    ServiceLogsFromJSON,
    ServiceLogsToJSON,
    SetMetadataRequestFromJSON,
    SetMetadataRequestToJSON,
    UpdateAppLocationSetting402ResponseFromJSON,
    UpdateAppLocationSetting402ResponseToJSON,
} from '../models/index';

export interface DockerServiceApiCheckServerDnsRequest {
    app: number;
    dockerService: number;
}

export interface DockerServiceApiCreateBackupRequest {
    dockerService: number;
    createBackupDockerServiceRequest: CreateBackupDockerServiceRequest;
}

export interface DockerServiceApiDockerServicesMetadataDeleteAllRequest {
    dockerService: number;
}

export interface DockerServiceApiDockerServicesMetadataDeleteKeysRequest {
    dockerService: number;
    metadata: Array<string>;
}

export interface DockerServiceApiDockerServicesMetadataSetRequest {
    dockerService: number;
    setMetadataRequest?: SetMetadataRequest;
}

export interface DockerServiceApiDockerServicesMetadataUpdateRequest {
    dockerService: number;
    patchMetadataRequest?: PatchMetadataRequest;
}

export interface DockerServiceApiDownloadServerLogsRequest {
    dockerService: number;
    streamSource?: DownloadServerLogsStreamSourceEnum;
}

export interface DockerServiceApiGetBackupsRequest {
    dockerService: number;
    perPage?: number;
    page?: number;
    sort?: Array<GetBackupsSortEnum>;
    filterName?: string;
    filterArchiveName?: string;
}

export interface DockerServiceApiGetLatestBackupRequest {
    dockerService: number;
}

export interface DockerServiceApiGetServerBackupDownloadUrlRequest {
    dockerService: number;
}

export interface DockerServiceApiGetServerByIdRequest {
    app: number;
    dockerService: number;
}

export interface DockerServiceApiGetServerLogsRequest {
    dockerService: number;
    limit?: number;
    direction?: string;
    streamSource?: GetServerLogsStreamSourceEnum;
}

export interface DockerServiceApiGetServersRequest {
    app: number;
    perPage?: number;
    page?: number;
    filterStatus?: string;
    filterAppLocationSettingId?: number;
    filterAutoscalingEnabled?: boolean;
    filterServerConfigId?: number;
    filterServerConfigName?: string;
    filterServerConfigNamePartial?: string;
    filterLocationCity?: string;
    filterLocationCityDisplay?: string;
    filterLocationContinent?: string;
    filterLocationCountry?: string;
    filterIsBackupable?: boolean;
    filterIsRestorable?: boolean;
    filterIsPending?: boolean;
    filterIsNotFound?: boolean;
    filterIsHealthy?: boolean;
    filterBinaryId?: number;
    filterIsStopped?: boolean;
    filterMetadata?: string;
    sort?: Array<GetServersSortEnum>;
}

export interface DockerServiceApiRestartServerRequest {
    dockerService: number;
}

export interface DockerServiceApiRestoreBackupRequest {
    dockerService: number;
}

export interface DockerServiceApiStartServerRequest {
    dockerService: number;
}

export interface DockerServiceApiStopServerRequest {
    dockerService: number;
}

/**
 * 
 */
export class DockerServiceApi extends runtime.BaseAPI {

    /**
     * Check URL reachability for service DNS URLs
     */
    async checkServerDnsRaw(requestParameters: DockerServiceApiCheckServerDnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DockerServiceDnsReachable>>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling checkServerDns().'
            );
        }

        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling checkServerDns().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services/{dockerService}/dns`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DockerServiceDnsReachableFromJSON));
    }

    /**
     * Check URL reachability for service DNS URLs
     */
    async checkServerDns(requestParameters: DockerServiceApiCheckServerDnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DockerServiceDnsReachable>> {
        const response = await this.checkServerDnsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create service backup
     */
    async createBackupRaw(requestParameters: DockerServiceApiCreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling createBackup().'
            );
        }

        if (requestParameters['createBackupDockerServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createBackupDockerServiceRequest',
                'Required parameter "createBackupDockerServiceRequest" was null or undefined when calling createBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/services/{dockerService}/backup`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBackupDockerServiceRequestToJSON(requestParameters['createBackupDockerServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create service backup
     */
    async createBackup(requestParameters: DockerServiceApiCreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createBackupRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all service metadata
     */
    async dockerServicesMetadataDeleteAllRaw(requestParameters: DockerServiceApiDockerServicesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataDeleteAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/metadata`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Delete all service metadata
     */
    async dockerServicesMetadataDeleteAll(requestParameters: DockerServiceApiDockerServicesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataDeleteAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete service metadata keys
     */
    async dockerServicesMetadataDeleteKeysRaw(requestParameters: DockerServiceApiDockerServicesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataDeleteKeys().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling dockerServicesMetadataDeleteKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata[]'] = requestParameters['metadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/metadata/keys`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Delete service metadata keys
     */
    async dockerServicesMetadataDeleteKeys(requestParameters: DockerServiceApiDockerServicesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataDeleteKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the entire metadata set with only the values provided in the request.
     * Set service metadata
     */
    async dockerServicesMetadataSetRaw(requestParameters: DockerServiceApiDockerServicesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/services/{dockerService}/metadata`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetMetadataRequestToJSON(requestParameters['setMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Replaces the entire metadata set with only the values provided in the request.
     * Set service metadata
     */
    async dockerServicesMetadataSet(requestParameters: DockerServiceApiDockerServicesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting metadata that is not mentioned.
     * Update service metadata
     */
    async dockerServicesMetadataUpdateRaw(requestParameters: DockerServiceApiDockerServicesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/services/{dockerService}/metadata`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchMetadataRequestToJSON(requestParameters['patchMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting metadata that is not mentioned.
     * Update service metadata
     */
    async dockerServicesMetadataUpdate(requestParameters: DockerServiceApiDockerServicesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download service logs
     */
    async downloadServerLogsRaw(requestParameters: DockerServiceApiDownloadServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceLogs>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling downloadServerLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['streamSource'] != null) {
            queryParameters['streamSource'] = requestParameters['streamSource'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/logs/download`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceLogsFromJSON(jsonValue));
    }

    /**
     * Download service logs
     */
    async downloadServerLogs(requestParameters: DockerServiceApiDownloadServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceLogs> {
        const response = await this.downloadServerLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List service backups
     */
    async getBackupsRaw(requestParameters: DockerServiceApiGetBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBackups200Response>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getBackups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterArchiveName'] != null) {
            queryParameters['filter[archiveName]'] = requestParameters['filterArchiveName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/backups`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBackups200ResponseFromJSON(jsonValue));
    }

    /**
     * List service backups
     */
    async getBackups(requestParameters: DockerServiceApiGetBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBackups200Response> {
        const response = await this.getBackupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get latest service backup
     */
    async getLatestBackupRaw(requestParameters: DockerServiceApiGetLatestBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Backup>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getLatestBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/backup`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupFromJSON(jsonValue));
    }

    /**
     * Get latest service backup
     */
    async getLatestBackup(requestParameters: DockerServiceApiGetLatestBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Backup> {
        const response = await this.getLatestBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get service backup download URL
     */
    async getServerBackupDownloadUrlRaw(requestParameters: DockerServiceApiGetServerBackupDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupDownload>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getServerBackupDownloadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/backup/download`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupDownloadFromJSON(jsonValue));
    }

    /**
     * Get service backup download URL
     */
    async getServerBackupDownloadUrl(requestParameters: DockerServiceApiGetServerBackupDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupDownload> {
        const response = await this.getServerBackupDownloadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Display a specific service
     */
    async getServerByIdRaw(requestParameters: DockerServiceApiGetServerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getServerById().'
            );
        }

        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getServerById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services/{dockerService}`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Display a specific service
     */
    async getServerById(requestParameters: DockerServiceApiGetServerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.getServerByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get service logs
     */
    async getServerLogsRaw(requestParameters: DockerServiceApiGetServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceLogs>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getServerLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['streamSource'] != null) {
            queryParameters['streamSource'] = requestParameters['streamSource'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/logs`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceLogsFromJSON(jsonValue));
    }

    /**
     * Get service logs
     */
    async getServerLogs(requestParameters: DockerServiceApiGetServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceLogs> {
        const response = await this.getServerLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List services
     */
    async getServersRaw(requestParameters: DockerServiceApiGetServersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetServers200Response>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getServers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterAppLocationSettingId'] != null) {
            queryParameters['filter[appLocationSettingId]'] = requestParameters['filterAppLocationSettingId'];
        }

        if (requestParameters['filterAutoscalingEnabled'] != null) {
            queryParameters['filter[autoscalingEnabled]'] = requestParameters['filterAutoscalingEnabled'];
        }

        if (requestParameters['filterServerConfigId'] != null) {
            queryParameters['filter[serverConfigId]'] = requestParameters['filterServerConfigId'];
        }

        if (requestParameters['filterServerConfigName'] != null) {
            queryParameters['filter[serverConfigName]'] = requestParameters['filterServerConfigName'];
        }

        if (requestParameters['filterServerConfigNamePartial'] != null) {
            queryParameters['filter[serverConfigNamePartial]'] = requestParameters['filterServerConfigNamePartial'];
        }

        if (requestParameters['filterLocationCity'] != null) {
            queryParameters['filter[locationCity]'] = requestParameters['filterLocationCity'];
        }

        if (requestParameters['filterLocationCityDisplay'] != null) {
            queryParameters['filter[locationCityDisplay]'] = requestParameters['filterLocationCityDisplay'];
        }

        if (requestParameters['filterLocationContinent'] != null) {
            queryParameters['filter[locationContinent]'] = requestParameters['filterLocationContinent'];
        }

        if (requestParameters['filterLocationCountry'] != null) {
            queryParameters['filter[locationCountry]'] = requestParameters['filterLocationCountry'];
        }

        if (requestParameters['filterIsBackupable'] != null) {
            queryParameters['filter[isBackupable]'] = requestParameters['filterIsBackupable'];
        }

        if (requestParameters['filterIsRestorable'] != null) {
            queryParameters['filter[isRestorable]'] = requestParameters['filterIsRestorable'];
        }

        if (requestParameters['filterIsPending'] != null) {
            queryParameters['filter[isPending]'] = requestParameters['filterIsPending'];
        }

        if (requestParameters['filterIsNotFound'] != null) {
            queryParameters['filter[isNotFound]'] = requestParameters['filterIsNotFound'];
        }

        if (requestParameters['filterIsHealthy'] != null) {
            queryParameters['filter[isHealthy]'] = requestParameters['filterIsHealthy'];
        }

        if (requestParameters['filterBinaryId'] != null) {
            queryParameters['filter[binaryId]'] = requestParameters['filterBinaryId'];
        }

        if (requestParameters['filterIsStopped'] != null) {
            queryParameters['filter[isStopped]'] = requestParameters['filterIsStopped'];
        }

        if (requestParameters['filterMetadata'] != null) {
            queryParameters['filter[metadata]'] = requestParameters['filterMetadata'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetServers200ResponseFromJSON(jsonValue));
    }

    /**
     * List services
     */
    async getServers(requestParameters: DockerServiceApiGetServersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetServers200Response> {
        const response = await this.getServersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restart service
     */
    async restartServerRaw(requestParameters: DockerServiceApiRestartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling restartServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/restart`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Restart service
     */
    async restartServer(requestParameters: DockerServiceApiRestartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.restartServerRaw(requestParameters, initOverrides);
    }

    /**
     * Restore latest service backup
     */
    async restoreBackupRaw(requestParameters: DockerServiceApiRestoreBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling restoreBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/restore`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Restore latest service backup
     */
    async restoreBackup(requestParameters: DockerServiceApiRestoreBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.restoreBackupRaw(requestParameters, initOverrides);
    }

    /**
     * Start service
     */
    async startServerRaw(requestParameters: DockerServiceApiStartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling startServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/start`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start service
     */
    async startServer(requestParameters: DockerServiceApiStartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startServerRaw(requestParameters, initOverrides);
    }

    /**
     * Stop service
     */
    async stopServerRaw(requestParameters: DockerServiceApiStopServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling stopServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/stop`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop service
     */
    async stopServer(requestParameters: DockerServiceApiStopServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.stopServerRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const DownloadServerLogsStreamSourceEnum = {
    Stdout: 'stdout',
    Stderr: 'stderr'
} as const;
export type DownloadServerLogsStreamSourceEnum = typeof DownloadServerLogsStreamSourceEnum[keyof typeof DownloadServerLogsStreamSourceEnum];
/**
 * @export
 */
export const GetBackupsSortEnum = {
    Name: '-name',
    Name2: 'name',
    ArchiveName: '-archiveName',
    ArchiveName2: 'archiveName',
    CreatedAt: '-createdAt',
    CreatedAt2: 'createdAt',
    RestoredAt: '-restoredAt',
    RestoredAt2: 'restoredAt'
} as const;
export type GetBackupsSortEnum = typeof GetBackupsSortEnum[keyof typeof GetBackupsSortEnum];
/**
 * @export
 */
export const GetServerLogsStreamSourceEnum = {
    Stdout: 'stdout',
    Stderr: 'stderr'
} as const;
export type GetServerLogsStreamSourceEnum = typeof GetServerLogsStreamSourceEnum[keyof typeof GetServerLogsStreamSourceEnum];
/**
 * @export
 */
export const GetServersSortEnum = {
    Id: '-id',
    Id2: 'id',
    Instance: '-instance',
    Instance2: 'instance',
    Status: '-status',
    Status2: 'status',
    StatusMessage: '-status_message',
    StatusMessage2: 'status_message',
    ServerConfigId: '-serverConfigId',
    ServerConfigId2: 'serverConfigId',
    ServerConfigName: '-serverConfigName',
    ServerConfigName2: 'serverConfigName',
    AppLocationSettingId: '-appLocationSettingId',
    AppLocationSettingId2: 'appLocationSettingId',
    Name: '-name',
    Name2: 'name',
    LocationCity: '-locationCity',
    LocationCity2: 'locationCity',
    LocationCityDisplay: '-locationCityDisplay',
    LocationCityDisplay2: 'locationCityDisplay',
    LocationContinent: '-locationContinent',
    LocationContinent2: 'locationContinent',
    LocationCountry: '-locationCountry',
    LocationCountry2: 'locationCountry',
    IsBackupable: 'isBackupable',
    IsBackupable2: '-isBackupable',
    IsRestorable: 'isRestorable',
    IsRestorable2: '-isRestorable',
    IsPending: 'isPending',
    IsPending2: '-isPending',
    IsNotFound: 'isNotFound',
    IsNotFound2: '-isNotFound',
    IsHealthy: 'isHealthy',
    IsHealthy2: '-isHealthy',
    IsStopped: 'isStopped',
    IsStopped2: '-isStopped',
    CreatedAt: '-createdAt',
    CreatedAt2: 'createdAt',
    UpdatedAt: '-updatedAt',
    UpdatedAt2: 'updatedAt'
} as const;
export type GetServersSortEnum = typeof GetServersSortEnum[keyof typeof GetServersSortEnum];
