/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Backup,
  BackupDownload,
  CreateBackupDockerServiceRequest,
  DockerRegistry,
  DockerServiceDnsReachable,
  GetAuthTokenViaFsid403Response,
  GetBackups200Response,
  GetDockerRegistries200Response,
  GetServers200Response,
  GetTaggedImages200Response,
  InlineObject,
  PatchDockerRegistryMetadataRequest,
  PatchMetadataRequest,
  Server,
  ServiceLogs,
  SetDockerRegistryMetadataRequest,
  SetMetadataRequest,
  StoreDockerRegistryRequest,
  UpdateAppLocationSetting402Response,
  UpdateDockerRegistryRequest,
} from '../models/index';
import {
    BackupFromJSON,
    BackupToJSON,
    BackupDownloadFromJSON,
    BackupDownloadToJSON,
    CreateBackupDockerServiceRequestFromJSON,
    CreateBackupDockerServiceRequestToJSON,
    DockerRegistryFromJSON,
    DockerRegistryToJSON,
    DockerServiceDnsReachableFromJSON,
    DockerServiceDnsReachableToJSON,
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    GetBackups200ResponseFromJSON,
    GetBackups200ResponseToJSON,
    GetDockerRegistries200ResponseFromJSON,
    GetDockerRegistries200ResponseToJSON,
    GetServers200ResponseFromJSON,
    GetServers200ResponseToJSON,
    GetTaggedImages200ResponseFromJSON,
    GetTaggedImages200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    PatchDockerRegistryMetadataRequestFromJSON,
    PatchDockerRegistryMetadataRequestToJSON,
    PatchMetadataRequestFromJSON,
    PatchMetadataRequestToJSON,
    ServerFromJSON,
    ServerToJSON,
    ServiceLogsFromJSON,
    ServiceLogsToJSON,
    SetDockerRegistryMetadataRequestFromJSON,
    SetDockerRegistryMetadataRequestToJSON,
    SetMetadataRequestFromJSON,
    SetMetadataRequestToJSON,
    StoreDockerRegistryRequestFromJSON,
    StoreDockerRegistryRequestToJSON,
    UpdateAppLocationSetting402ResponseFromJSON,
    UpdateAppLocationSetting402ResponseToJSON,
    UpdateDockerRegistryRequestFromJSON,
    UpdateDockerRegistryRequestToJSON,
} from '../models/index';

export interface DockerApiCheckServerDnsRequest {
    app: number;
    dockerService: number;
}

export interface DockerApiCreateBackupRequest {
    dockerService: number;
    createBackupDockerServiceRequest: CreateBackupDockerServiceRequest;
}

export interface DockerApiCreateDockerRegistryRequest {
    storeDockerRegistryRequest: StoreDockerRegistryRequest;
}

export interface DockerApiDeleteDockerRegistryRequest {
    dockerRegistry: number;
}

export interface DockerApiDockerRegistriesMetadataDeleteAllRequest {
    dockerRegistry: number;
}

export interface DockerApiDockerRegistriesMetadataDeleteKeysRequest {
    dockerRegistry: number;
    metadata: Array<string>;
}

export interface DockerApiDockerRegistriesMetadataSetRequest {
    dockerRegistry: number;
    setDockerRegistryMetadataRequest?: SetDockerRegistryMetadataRequest;
}

export interface DockerApiDockerRegistriesMetadataUpdateRequest {
    dockerRegistry: number;
    patchDockerRegistryMetadataRequest?: PatchDockerRegistryMetadataRequest;
}

export interface DockerApiDockerServicesAutoscalingAllocateRequest {
    dockerService: number;
}

export interface DockerApiDockerServicesAutoscalingHealthRequest {
    dockerService: number;
}

export interface DockerApiDockerServicesAutoscalingReadyRequest {
    dockerService: number;
}

export interface DockerApiDockerServicesAutoscalingShutdownRequest {
    dockerService: number;
}

export interface DockerApiDockerServicesMetadataDeleteAllRequest {
    dockerService: number;
}

export interface DockerApiDockerServicesMetadataDeleteKeysRequest {
    dockerService: number;
    metadata: Array<string>;
}

export interface DockerApiDockerServicesMetadataSetRequest {
    dockerService: number;
    setMetadataRequest?: SetMetadataRequest;
}

export interface DockerApiDockerServicesMetadataUpdateRequest {
    dockerService: number;
    patchMetadataRequest?: PatchMetadataRequest;
}

export interface DockerApiDownloadServerLogsRequest {
    dockerService: number;
    streamSource?: DownloadServerLogsStreamSourceEnum;
}

export interface DockerApiGetBackupsRequest {
    dockerService: number;
    perPage?: number;
    page?: number;
    sort?: Array<GetBackupsSortEnum>;
    filterName?: string;
    filterArchiveName?: string;
}

export interface DockerApiGetDockerRegistriesRequest {
    perPage?: number;
    page?: number;
    sort?: Array<GetDockerRegistriesSortEnum>;
    filterId?: number;
    filterType?: string;
    filterName?: string;
    filterNamePartial?: string;
    filterUrl?: string;
    filterOrganization?: string;
    filterMetadata?: string;
}

export interface DockerApiGetDockerRegistryByIdRequest {
    dockerRegistry: number;
}

export interface DockerApiGetLatestBackupRequest {
    dockerService: number;
}

export interface DockerApiGetServerBackupDownloadUrlRequest {
    dockerService: number;
}

export interface DockerApiGetServerByIdRequest {
    app: number;
    dockerService: number;
}

export interface DockerApiGetServerLogsRequest {
    dockerService: number;
    limit?: number;
    direction?: string;
    streamSource?: GetServerLogsStreamSourceEnum;
}

export interface DockerApiGetServersRequest {
    app: number;
    perPage?: number;
    page?: number;
    filterStatus?: string;
    filterAppLocationSettingId?: number;
    filterAutoscalingEnabled?: boolean;
    filterServerConfigId?: number;
    filterServerConfigName?: string;
    filterServerConfigNamePartial?: string;
    filterLocationCity?: string;
    filterLocationCityDisplay?: string;
    filterLocationContinent?: string;
    filterLocationCountry?: string;
    filterIsBackupable?: boolean;
    filterIsRestorable?: boolean;
    filterIsPending?: boolean;
    filterIsNotFound?: boolean;
    filterIsHealthy?: boolean;
    filterBinaryId?: number;
    filterIsStopped?: boolean;
    filterMetadata?: string;
    sort?: Array<GetServersSortEnum>;
}

export interface DockerApiGetTaggedImagesRequest {
    dockerRegistry: number;
}

export interface DockerApiRefreshTaggedImagesRequest {
    dockerRegistry: number;
}

export interface DockerApiRestartServerRequest {
    dockerService: number;
}

export interface DockerApiRestoreBackupRequest {
    dockerService: number;
}

export interface DockerApiStartServerRequest {
    dockerService: number;
}

export interface DockerApiStopServerRequest {
    dockerService: number;
}

export interface DockerApiUpdateDockerRegistryOperationRequest {
    dockerRegistry: number;
    updateDockerRegistryRequest: UpdateDockerRegistryRequest;
}

/**
 * 
 */
export class DockerApi extends runtime.BaseAPI {

    /**
     * Check URL reachability for service DNS URLs
     */
    async checkServerDnsRaw(requestParameters: DockerApiCheckServerDnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DockerServiceDnsReachable>>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling checkServerDns().'
            );
        }

        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling checkServerDns().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services/{dockerService}/dns`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DockerServiceDnsReachableFromJSON));
    }

    /**
     * Check URL reachability for service DNS URLs
     */
    async checkServerDns(requestParameters: DockerApiCheckServerDnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DockerServiceDnsReachable>> {
        const response = await this.checkServerDnsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create service backup
     */
    async createBackupRaw(requestParameters: DockerApiCreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling createBackup().'
            );
        }

        if (requestParameters['createBackupDockerServiceRequest'] == null) {
            throw new runtime.RequiredError(
                'createBackupDockerServiceRequest',
                'Required parameter "createBackupDockerServiceRequest" was null or undefined when calling createBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/services/{dockerService}/backup`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateBackupDockerServiceRequestToJSON(requestParameters['createBackupDockerServiceRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Create service backup
     */
    async createBackup(requestParameters: DockerApiCreateBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createBackupRaw(requestParameters, initOverrides);
    }

    /**
     * Create a new docker registry
     */
    async createDockerRegistryRaw(requestParameters: DockerApiCreateDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['storeDockerRegistryRequest'] == null) {
            throw new runtime.RequiredError(
                'storeDockerRegistryRequest',
                'Required parameter "storeDockerRegistryRequest" was null or undefined when calling createDockerRegistry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreDockerRegistryRequestToJSON(requestParameters['storeDockerRegistryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Create a new docker registry
     */
    async createDockerRegistry(requestParameters: DockerApiCreateDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.createDockerRegistryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific docker registry
     */
    async deleteDockerRegistryRaw(requestParameters: DockerApiDeleteDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling deleteDockerRegistry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specific docker registry
     */
    async deleteDockerRegistry(requestParameters: DockerApiDeleteDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDockerRegistryRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all metadata
     */
    async dockerRegistriesMetadataDeleteAllRaw(requestParameters: DockerApiDockerRegistriesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataDeleteAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Delete all metadata
     */
    async dockerRegistriesMetadataDeleteAll(requestParameters: DockerApiDockerRegistriesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataDeleteAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete metadata keys
     */
    async dockerRegistriesMetadataDeleteKeysRaw(requestParameters: DockerApiDockerRegistriesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataDeleteKeys().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling dockerRegistriesMetadataDeleteKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata[]'] = requestParameters['metadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata/keys`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Delete metadata keys
     */
    async dockerRegistriesMetadataDeleteKeys(requestParameters: DockerApiDockerRegistriesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataDeleteKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the entire metadata.
     * Set metadata
     */
    async dockerRegistriesMetadataSetRaw(requestParameters: DockerApiDockerRegistriesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetDockerRegistryMetadataRequestToJSON(requestParameters['setDockerRegistryMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Replaces the entire metadata.
     * Set metadata
     */
    async dockerRegistriesMetadataSet(requestParameters: DockerApiDockerRegistriesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting other metadata.
     * Update metadata
     */
    async dockerRegistriesMetadataUpdateRaw(requestParameters: DockerApiDockerRegistriesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchDockerRegistryMetadataRequestToJSON(requestParameters['patchDockerRegistryMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting other metadata.
     * Update metadata
     */
    async dockerRegistriesMetadataUpdate(requestParameters: DockerApiDockerRegistriesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Set autoscaling status to allocated
     */
    async dockerServicesAutoscalingAllocateRaw(requestParameters: DockerApiDockerServicesAutoscalingAllocateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesAutoscalingAllocate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/autoscaling/allocate`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set autoscaling status to allocated
     */
    async dockerServicesAutoscalingAllocate(requestParameters: DockerApiDockerServicesAutoscalingAllocateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dockerServicesAutoscalingAllocateRaw(requestParameters, initOverrides);
    }

    /**
     * Record an autoscaling heartbeat
     */
    async dockerServicesAutoscalingHealthRaw(requestParameters: DockerApiDockerServicesAutoscalingHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesAutoscalingHealth().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/autoscaling/health`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Record an autoscaling heartbeat
     */
    async dockerServicesAutoscalingHealth(requestParameters: DockerApiDockerServicesAutoscalingHealthRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dockerServicesAutoscalingHealthRaw(requestParameters, initOverrides);
    }

    /**
     * Set autoscaling status to ready
     */
    async dockerServicesAutoscalingReadyRaw(requestParameters: DockerApiDockerServicesAutoscalingReadyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesAutoscalingReady().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/autoscaling/ready`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set autoscaling status to ready
     */
    async dockerServicesAutoscalingReady(requestParameters: DockerApiDockerServicesAutoscalingReadyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dockerServicesAutoscalingReadyRaw(requestParameters, initOverrides);
    }

    /**
     * Set autoscaling status to shutdown
     */
    async dockerServicesAutoscalingShutdownRaw(requestParameters: DockerApiDockerServicesAutoscalingShutdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesAutoscalingShutdown().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/autoscaling/shutdown`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set autoscaling status to shutdown
     */
    async dockerServicesAutoscalingShutdown(requestParameters: DockerApiDockerServicesAutoscalingShutdownRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.dockerServicesAutoscalingShutdownRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all service metadata
     */
    async dockerServicesMetadataDeleteAllRaw(requestParameters: DockerApiDockerServicesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataDeleteAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/metadata`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Delete all service metadata
     */
    async dockerServicesMetadataDeleteAll(requestParameters: DockerApiDockerServicesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataDeleteAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete service metadata keys
     */
    async dockerServicesMetadataDeleteKeysRaw(requestParameters: DockerApiDockerServicesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataDeleteKeys().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling dockerServicesMetadataDeleteKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata[]'] = requestParameters['metadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/metadata/keys`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Delete service metadata keys
     */
    async dockerServicesMetadataDeleteKeys(requestParameters: DockerApiDockerServicesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataDeleteKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the entire metadata set with only the values provided in the request.
     * Set service metadata
     */
    async dockerServicesMetadataSetRaw(requestParameters: DockerApiDockerServicesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/services/{dockerService}/metadata`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetMetadataRequestToJSON(requestParameters['setMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Replaces the entire metadata set with only the values provided in the request.
     * Set service metadata
     */
    async dockerServicesMetadataSet(requestParameters: DockerApiDockerServicesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting metadata that is not mentioned.
     * Update service metadata
     */
    async dockerServicesMetadataUpdateRaw(requestParameters: DockerApiDockerServicesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling dockerServicesMetadataUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/services/{dockerService}/metadata`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchMetadataRequestToJSON(requestParameters['patchMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting metadata that is not mentioned.
     * Update service metadata
     */
    async dockerServicesMetadataUpdate(requestParameters: DockerApiDockerServicesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.dockerServicesMetadataUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Download service logs
     */
    async downloadServerLogsRaw(requestParameters: DockerApiDownloadServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceLogs>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling downloadServerLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['streamSource'] != null) {
            queryParameters['streamSource'] = requestParameters['streamSource'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/logs/download`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceLogsFromJSON(jsonValue));
    }

    /**
     * Download service logs
     */
    async downloadServerLogs(requestParameters: DockerApiDownloadServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceLogs> {
        const response = await this.downloadServerLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List service backups
     */
    async getBackupsRaw(requestParameters: DockerApiGetBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBackups200Response>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getBackups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterArchiveName'] != null) {
            queryParameters['filter[archiveName]'] = requestParameters['filterArchiveName'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/backups`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetBackups200ResponseFromJSON(jsonValue));
    }

    /**
     * List service backups
     */
    async getBackups(requestParameters: DockerApiGetBackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBackups200Response> {
        const response = await this.getBackupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show all docker registries
     */
    async getDockerRegistriesRaw(requestParameters: DockerApiGetDockerRegistriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDockerRegistries200Response>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }

        if (requestParameters['filterUrl'] != null) {
            queryParameters['filter[url]'] = requestParameters['filterUrl'];
        }

        if (requestParameters['filterOrganization'] != null) {
            queryParameters['filter[organization]'] = requestParameters['filterOrganization'];
        }

        if (requestParameters['filterMetadata'] != null) {
            queryParameters['filter[metadata]'] = requestParameters['filterMetadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDockerRegistries200ResponseFromJSON(jsonValue));
    }

    /**
     * Show all docker registries
     */
    async getDockerRegistries(requestParameters: DockerApiGetDockerRegistriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDockerRegistries200Response> {
        const response = await this.getDockerRegistriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Display a specific docker registry
     */
    async getDockerRegistryByIdRaw(requestParameters: DockerApiGetDockerRegistryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling getDockerRegistryById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Display a specific docker registry
     */
    async getDockerRegistryById(requestParameters: DockerApiGetDockerRegistryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.getDockerRegistryByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get latest service backup
     */
    async getLatestBackupRaw(requestParameters: DockerApiGetLatestBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Backup>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getLatestBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/backup`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupFromJSON(jsonValue));
    }

    /**
     * Get latest service backup
     */
    async getLatestBackup(requestParameters: DockerApiGetLatestBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Backup> {
        const response = await this.getLatestBackupRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get service backup download URL
     */
    async getServerBackupDownloadUrlRaw(requestParameters: DockerApiGetServerBackupDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BackupDownload>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getServerBackupDownloadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/backup/download`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BackupDownloadFromJSON(jsonValue));
    }

    /**
     * Get service backup download URL
     */
    async getServerBackupDownloadUrl(requestParameters: DockerApiGetServerBackupDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BackupDownload> {
        const response = await this.getServerBackupDownloadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Display a specific service
     */
    async getServerByIdRaw(requestParameters: DockerApiGetServerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Server>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getServerById().'
            );
        }

        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getServerById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services/{dockerService}`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServerFromJSON(jsonValue));
    }

    /**
     * Display a specific service
     */
    async getServerById(requestParameters: DockerApiGetServerByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Server> {
        const response = await this.getServerByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get service logs
     */
    async getServerLogsRaw(requestParameters: DockerApiGetServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ServiceLogs>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling getServerLogs().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['direction'] != null) {
            queryParameters['direction'] = requestParameters['direction'];
        }

        if (requestParameters['streamSource'] != null) {
            queryParameters['streamSource'] = requestParameters['streamSource'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/logs`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ServiceLogsFromJSON(jsonValue));
    }

    /**
     * Get service logs
     */
    async getServerLogs(requestParameters: DockerApiGetServerLogsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ServiceLogs> {
        const response = await this.getServerLogsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List services
     */
    async getServersRaw(requestParameters: DockerApiGetServersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetServers200Response>> {
        if (requestParameters['app'] == null) {
            throw new runtime.RequiredError(
                'app',
                'Required parameter "app" was null or undefined when calling getServers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['filterStatus'] != null) {
            queryParameters['filter[status]'] = requestParameters['filterStatus'];
        }

        if (requestParameters['filterAppLocationSettingId'] != null) {
            queryParameters['filter[appLocationSettingId]'] = requestParameters['filterAppLocationSettingId'];
        }

        if (requestParameters['filterAutoscalingEnabled'] != null) {
            queryParameters['filter[autoscalingEnabled]'] = requestParameters['filterAutoscalingEnabled'];
        }

        if (requestParameters['filterServerConfigId'] != null) {
            queryParameters['filter[serverConfigId]'] = requestParameters['filterServerConfigId'];
        }

        if (requestParameters['filterServerConfigName'] != null) {
            queryParameters['filter[serverConfigName]'] = requestParameters['filterServerConfigName'];
        }

        if (requestParameters['filterServerConfigNamePartial'] != null) {
            queryParameters['filter[serverConfigNamePartial]'] = requestParameters['filterServerConfigNamePartial'];
        }

        if (requestParameters['filterLocationCity'] != null) {
            queryParameters['filter[locationCity]'] = requestParameters['filterLocationCity'];
        }

        if (requestParameters['filterLocationCityDisplay'] != null) {
            queryParameters['filter[locationCityDisplay]'] = requestParameters['filterLocationCityDisplay'];
        }

        if (requestParameters['filterLocationContinent'] != null) {
            queryParameters['filter[locationContinent]'] = requestParameters['filterLocationContinent'];
        }

        if (requestParameters['filterLocationCountry'] != null) {
            queryParameters['filter[locationCountry]'] = requestParameters['filterLocationCountry'];
        }

        if (requestParameters['filterIsBackupable'] != null) {
            queryParameters['filter[isBackupable]'] = requestParameters['filterIsBackupable'];
        }

        if (requestParameters['filterIsRestorable'] != null) {
            queryParameters['filter[isRestorable]'] = requestParameters['filterIsRestorable'];
        }

        if (requestParameters['filterIsPending'] != null) {
            queryParameters['filter[isPending]'] = requestParameters['filterIsPending'];
        }

        if (requestParameters['filterIsNotFound'] != null) {
            queryParameters['filter[isNotFound]'] = requestParameters['filterIsNotFound'];
        }

        if (requestParameters['filterIsHealthy'] != null) {
            queryParameters['filter[isHealthy]'] = requestParameters['filterIsHealthy'];
        }

        if (requestParameters['filterBinaryId'] != null) {
            queryParameters['filter[binaryId]'] = requestParameters['filterBinaryId'];
        }

        if (requestParameters['filterIsStopped'] != null) {
            queryParameters['filter[isStopped]'] = requestParameters['filterIsStopped'];
        }

        if (requestParameters['filterMetadata'] != null) {
            queryParameters['filter[metadata]'] = requestParameters['filterMetadata'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/apps/{app}/services`;
        urlPath = urlPath.replace(`{${"app"}}`, encodeURIComponent(String(requestParameters['app'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetServers200ResponseFromJSON(jsonValue));
    }

    /**
     * List services
     */
    async getServers(requestParameters: DockerApiGetServersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetServers200Response> {
        const response = await this.getServersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all available tagged images
     */
    async getTaggedImagesRaw(requestParameters: DockerApiGetTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTaggedImages200Response>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling getTaggedImages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/tagged-images`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTaggedImages200ResponseFromJSON(jsonValue));
    }

    /**
     * List all available tagged images
     */
    async getTaggedImages(requestParameters: DockerApiGetTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTaggedImages200Response> {
        const response = await this.getTaggedImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh the cache for all available tagged images
     */
    async refreshTaggedImagesRaw(requestParameters: DockerApiRefreshTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTaggedImages200Response>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling refreshTaggedImages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/tagged-images/refresh`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTaggedImages200ResponseFromJSON(jsonValue));
    }

    /**
     * Refresh the cache for all available tagged images
     */
    async refreshTaggedImages(requestParameters: DockerApiRefreshTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTaggedImages200Response> {
        const response = await this.refreshTaggedImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Restart service
     */
    async restartServerRaw(requestParameters: DockerApiRestartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling restartServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/restart`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Restart service
     */
    async restartServer(requestParameters: DockerApiRestartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.restartServerRaw(requestParameters, initOverrides);
    }

    /**
     * Restore latest service backup
     */
    async restoreBackupRaw(requestParameters: DockerApiRestoreBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling restoreBackup().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/restore`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Restore latest service backup
     */
    async restoreBackup(requestParameters: DockerApiRestoreBackupRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.restoreBackupRaw(requestParameters, initOverrides);
    }

    /**
     * Start service
     */
    async startServerRaw(requestParameters: DockerApiStartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling startServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/start`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Start service
     */
    async startServer(requestParameters: DockerApiStartServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.startServerRaw(requestParameters, initOverrides);
    }

    /**
     * Stop service
     */
    async stopServerRaw(requestParameters: DockerApiStopServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerService'] == null) {
            throw new runtime.RequiredError(
                'dockerService',
                'Required parameter "dockerService" was null or undefined when calling stopServer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/services/{dockerService}/stop`;
        urlPath = urlPath.replace(`{${"dockerService"}}`, encodeURIComponent(String(requestParameters['dockerService'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Stop service
     */
    async stopServer(requestParameters: DockerApiStopServerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.stopServerRaw(requestParameters, initOverrides);
    }

    /**
     * Update a specific docker registry
     */
    async updateDockerRegistryRaw(requestParameters: DockerApiUpdateDockerRegistryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling updateDockerRegistry().'
            );
        }

        if (requestParameters['updateDockerRegistryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateDockerRegistryRequest',
                'Required parameter "updateDockerRegistryRequest" was null or undefined when calling updateDockerRegistry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDockerRegistryRequestToJSON(requestParameters['updateDockerRegistryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Update a specific docker registry
     */
    async updateDockerRegistry(requestParameters: DockerApiUpdateDockerRegistryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.updateDockerRegistryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const DownloadServerLogsStreamSourceEnum = {
    Stdout: 'stdout',
    Stderr: 'stderr'
} as const;
export type DownloadServerLogsStreamSourceEnum = typeof DownloadServerLogsStreamSourceEnum[keyof typeof DownloadServerLogsStreamSourceEnum];
/**
 * @export
 */
export const GetBackupsSortEnum = {
    Name: '-name',
    Name2: 'name',
    ArchiveName: '-archiveName',
    ArchiveName2: 'archiveName',
    CreatedAt: '-createdAt',
    CreatedAt2: 'createdAt',
    RestoredAt: '-restoredAt',
    RestoredAt2: 'restoredAt'
} as const;
export type GetBackupsSortEnum = typeof GetBackupsSortEnum[keyof typeof GetBackupsSortEnum];
/**
 * @export
 */
export const GetDockerRegistriesSortEnum = {
    Id: '-id',
    Id2: 'id',
    Type: '-type',
    Type2: 'type',
    Name: '-name',
    Name2: 'name',
    Url: '-url',
    Url2: 'url',
    Organization: '-organization',
    Organization2: 'organization'
} as const;
export type GetDockerRegistriesSortEnum = typeof GetDockerRegistriesSortEnum[keyof typeof GetDockerRegistriesSortEnum];
/**
 * @export
 */
export const GetServerLogsStreamSourceEnum = {
    Stdout: 'stdout',
    Stderr: 'stderr'
} as const;
export type GetServerLogsStreamSourceEnum = typeof GetServerLogsStreamSourceEnum[keyof typeof GetServerLogsStreamSourceEnum];
/**
 * @export
 */
export const GetServersSortEnum = {
    Id: '-id',
    Id2: 'id',
    Instance: '-instance',
    Instance2: 'instance',
    Status: '-status',
    Status2: 'status',
    StatusMessage: '-status_message',
    StatusMessage2: 'status_message',
    ServerConfigId: '-serverConfigId',
    ServerConfigId2: 'serverConfigId',
    ServerConfigName: '-serverConfigName',
    ServerConfigName2: 'serverConfigName',
    AppLocationSettingId: '-appLocationSettingId',
    AppLocationSettingId2: 'appLocationSettingId',
    Name: '-name',
    Name2: 'name',
    LocationCity: '-locationCity',
    LocationCity2: 'locationCity',
    LocationCityDisplay: '-locationCityDisplay',
    LocationCityDisplay2: 'locationCityDisplay',
    LocationContinent: '-locationContinent',
    LocationContinent2: 'locationContinent',
    LocationCountry: '-locationCountry',
    LocationCountry2: 'locationCountry',
    IsBackupable: 'isBackupable',
    IsBackupable2: '-isBackupable',
    IsRestorable: 'isRestorable',
    IsRestorable2: '-isRestorable',
    IsPending: 'isPending',
    IsPending2: '-isPending',
    IsNotFound: 'isNotFound',
    IsNotFound2: '-isNotFound',
    IsHealthy: 'isHealthy',
    IsHealthy2: '-isHealthy',
    IsStopped: 'isStopped',
    IsStopped2: '-isStopped',
    CreatedAt: '-createdAt',
    CreatedAt2: 'createdAt',
    UpdatedAt: '-updatedAt',
    UpdatedAt2: 'updatedAt'
} as const;
export type GetServersSortEnum = typeof GetServersSortEnum[keyof typeof GetServersSortEnum];
