/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DockerRegistry,
  GetAuthTokenViaFsid403Response,
  GetDockerRegistries200Response,
  GetTaggedImages200Response,
  InlineObject,
  PatchDockerRegistryMetadataRequest,
  SetDockerRegistryMetadataRequest,
  StoreDockerRegistryRequest,
  UpdateDockerRegistryRequest,
} from '../models/index';
import {
    DockerRegistryFromJSON,
    DockerRegistryToJSON,
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    GetDockerRegistries200ResponseFromJSON,
    GetDockerRegistries200ResponseToJSON,
    GetTaggedImages200ResponseFromJSON,
    GetTaggedImages200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    PatchDockerRegistryMetadataRequestFromJSON,
    PatchDockerRegistryMetadataRequestToJSON,
    SetDockerRegistryMetadataRequestFromJSON,
    SetDockerRegistryMetadataRequestToJSON,
    StoreDockerRegistryRequestFromJSON,
    StoreDockerRegistryRequestToJSON,
    UpdateDockerRegistryRequestFromJSON,
    UpdateDockerRegistryRequestToJSON,
} from '../models/index';

export interface DockerRegistryApiCreateDockerRegistryRequest {
    storeDockerRegistryRequest: StoreDockerRegistryRequest;
}

export interface DockerRegistryApiDeleteDockerRegistryRequest {
    dockerRegistry: number;
}

export interface DockerRegistryApiDockerRegistriesMetadataDeleteAllRequest {
    dockerRegistry: number;
}

export interface DockerRegistryApiDockerRegistriesMetadataDeleteKeysRequest {
    dockerRegistry: number;
    metadata: Array<string>;
}

export interface DockerRegistryApiDockerRegistriesMetadataSetRequest {
    dockerRegistry: number;
    setDockerRegistryMetadataRequest?: SetDockerRegistryMetadataRequest;
}

export interface DockerRegistryApiDockerRegistriesMetadataUpdateRequest {
    dockerRegistry: number;
    patchDockerRegistryMetadataRequest?: PatchDockerRegistryMetadataRequest;
}

export interface DockerRegistryApiGetDockerRegistriesRequest {
    perPage?: number;
    page?: number;
    sort?: Array<GetDockerRegistriesSortEnum>;
    filterId?: number;
    filterType?: string;
    filterName?: string;
    filterNamePartial?: string;
    filterUrl?: string;
    filterOrganization?: string;
    filterMetadata?: string;
}

export interface DockerRegistryApiGetDockerRegistryByIdRequest {
    dockerRegistry: number;
}

export interface DockerRegistryApiGetTaggedImagesRequest {
    dockerRegistry: number;
}

export interface DockerRegistryApiRefreshTaggedImagesRequest {
    dockerRegistry: number;
}

export interface DockerRegistryApiUpdateDockerRegistryOperationRequest {
    dockerRegistry: number;
    updateDockerRegistryRequest: UpdateDockerRegistryRequest;
}

/**
 * 
 */
export class DockerRegistryApi extends runtime.BaseAPI {

    /**
     * Create a new docker registry
     */
    async createDockerRegistryRaw(requestParameters: DockerRegistryApiCreateDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['storeDockerRegistryRequest'] == null) {
            throw new runtime.RequiredError(
                'storeDockerRegistryRequest',
                'Required parameter "storeDockerRegistryRequest" was null or undefined when calling createDockerRegistry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StoreDockerRegistryRequestToJSON(requestParameters['storeDockerRegistryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Create a new docker registry
     */
    async createDockerRegistry(requestParameters: DockerRegistryApiCreateDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.createDockerRegistryRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a specific docker registry
     */
    async deleteDockerRegistryRaw(requestParameters: DockerRegistryApiDeleteDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling deleteDockerRegistry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a specific docker registry
     */
    async deleteDockerRegistry(requestParameters: DockerRegistryApiDeleteDockerRegistryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteDockerRegistryRaw(requestParameters, initOverrides);
    }

    /**
     * Delete all metadata
     */
    async dockerRegistriesMetadataDeleteAllRaw(requestParameters: DockerRegistryApiDockerRegistriesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataDeleteAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Delete all metadata
     */
    async dockerRegistriesMetadataDeleteAll(requestParameters: DockerRegistryApiDockerRegistriesMetadataDeleteAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataDeleteAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete metadata keys
     */
    async dockerRegistriesMetadataDeleteKeysRaw(requestParameters: DockerRegistryApiDockerRegistriesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataDeleteKeys().'
            );
        }

        if (requestParameters['metadata'] == null) {
            throw new runtime.RequiredError(
                'metadata',
                'Required parameter "metadata" was null or undefined when calling dockerRegistriesMetadataDeleteKeys().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata[]'] = requestParameters['metadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata/keys`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Delete metadata keys
     */
    async dockerRegistriesMetadataDeleteKeys(requestParameters: DockerRegistryApiDockerRegistriesMetadataDeleteKeysRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataDeleteKeysRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Replaces the entire metadata.
     * Set metadata
     */
    async dockerRegistriesMetadataSetRaw(requestParameters: DockerRegistryApiDockerRegistriesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataSet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetDockerRegistryMetadataRequestToJSON(requestParameters['setDockerRegistryMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Replaces the entire metadata.
     * Set metadata
     */
    async dockerRegistriesMetadataSet(requestParameters: DockerRegistryApiDockerRegistriesMetadataSetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataSetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting other metadata.
     * Update metadata
     */
    async dockerRegistriesMetadataUpdateRaw(requestParameters: DockerRegistryApiDockerRegistriesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling dockerRegistriesMetadataUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries/{dockerRegistry}/metadata`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchDockerRegistryMetadataRequestToJSON(requestParameters['patchDockerRegistryMetadataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Updates existing metadata keys or adds new keys without deleting other metadata.
     * Update metadata
     */
    async dockerRegistriesMetadataUpdate(requestParameters: DockerRegistryApiDockerRegistriesMetadataUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.dockerRegistriesMetadataUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show all docker registries
     */
    async getDockerRegistriesRaw(requestParameters: DockerRegistryApiGetDockerRegistriesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetDockerRegistries200Response>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }

        if (requestParameters['filterUrl'] != null) {
            queryParameters['filter[url]'] = requestParameters['filterUrl'];
        }

        if (requestParameters['filterOrganization'] != null) {
            queryParameters['filter[organization]'] = requestParameters['filterOrganization'];
        }

        if (requestParameters['filterMetadata'] != null) {
            queryParameters['filter[metadata]'] = requestParameters['filterMetadata'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetDockerRegistries200ResponseFromJSON(jsonValue));
    }

    /**
     * Show all docker registries
     */
    async getDockerRegistries(requestParameters: DockerRegistryApiGetDockerRegistriesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetDockerRegistries200Response> {
        const response = await this.getDockerRegistriesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Display a specific docker registry
     */
    async getDockerRegistryByIdRaw(requestParameters: DockerRegistryApiGetDockerRegistryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling getDockerRegistryById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Display a specific docker registry
     */
    async getDockerRegistryById(requestParameters: DockerRegistryApiGetDockerRegistryByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.getDockerRegistryByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List all available tagged images
     */
    async getTaggedImagesRaw(requestParameters: DockerRegistryApiGetTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTaggedImages200Response>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling getTaggedImages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/tagged-images`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTaggedImages200ResponseFromJSON(jsonValue));
    }

    /**
     * List all available tagged images
     */
    async getTaggedImages(requestParameters: DockerRegistryApiGetTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTaggedImages200Response> {
        const response = await this.getTaggedImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Refresh the cache for all available tagged images
     */
    async refreshTaggedImagesRaw(requestParameters: DockerRegistryApiRefreshTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetTaggedImages200Response>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling refreshTaggedImages().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/docker-registries/{dockerRegistry}/tagged-images/refresh`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetTaggedImages200ResponseFromJSON(jsonValue));
    }

    /**
     * Refresh the cache for all available tagged images
     */
    async refreshTaggedImages(requestParameters: DockerRegistryApiRefreshTaggedImagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetTaggedImages200Response> {
        const response = await this.refreshTaggedImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a specific docker registry
     */
    async updateDockerRegistryRaw(requestParameters: DockerRegistryApiUpdateDockerRegistryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DockerRegistry>> {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError(
                'dockerRegistry',
                'Required parameter "dockerRegistry" was null or undefined when calling updateDockerRegistry().'
            );
        }

        if (requestParameters['updateDockerRegistryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateDockerRegistryRequest',
                'Required parameter "updateDockerRegistryRequest" was null or undefined when calling updateDockerRegistry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateDockerRegistryRequestToJSON(requestParameters['updateDockerRegistryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DockerRegistryFromJSON(jsonValue));
    }

    /**
     * Update a specific docker registry
     */
    async updateDockerRegistry(requestParameters: DockerRegistryApiUpdateDockerRegistryOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DockerRegistry> {
        const response = await this.updateDockerRegistryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetDockerRegistriesSortEnum = {
    Id: '-id',
    Id2: 'id',
    Type: '-type',
    Type2: 'type',
    Name: '-name',
    Name2: 'name',
    Url: '-url',
    Url2: 'url',
    Organization: '-organization',
    Organization2: 'organization'
} as const;
export type GetDockerRegistriesSortEnum = typeof GetDockerRegistriesSortEnum[keyof typeof GetDockerRegistriesSortEnum];
