/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAuthTokenViaFsid403Response,
  GetLocations200Response,
  InlineObject,
  OccupiedLocationRequest,
  UpdateAppLocationSetting402Response,
} from '../models/index';
import {
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    GetLocations200ResponseFromJSON,
    GetLocations200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    OccupiedLocationRequestFromJSON,
    OccupiedLocationRequestToJSON,
    UpdateAppLocationSetting402ResponseFromJSON,
    UpdateAppLocationSetting402ResponseToJSON,
} from '../models/index';

export interface NodesApiGetLocationsRequest {
    perPage?: number;
    page?: number;
}

export interface NodesApiRequestLocationRequest {
    occupiedLocationRequest: OccupiedLocationRequest;
}

/**
 * 
 */
export class NodesApi extends runtime.BaseAPI {

    /**
     * Show a unique listing of locations based on active and ready worker nodes
     */
    async getLocationsRaw(requestParameters: NodesApiGetLocationsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetLocations200Response>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/nodes/locations`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetLocations200ResponseFromJSON(jsonValue));
    }

    /**
     * Show a unique listing of locations based on active and ready worker nodes
     */
    async getLocations(requestParameters: NodesApiGetLocationsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetLocations200Response> {
        const response = await this.getLocationsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Submit a new location request
     */
    async requestLocationRaw(requestParameters: NodesApiRequestLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['occupiedLocationRequest'] == null) {
            throw new runtime.RequiredError(
                'occupiedLocationRequest',
                'Required parameter "occupiedLocationRequest" was null or undefined when calling requestLocation().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/v1/nodes/locations/request`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: OccupiedLocationRequestToJSON(requestParameters['occupiedLocationRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Submit a new location request
     */
    async requestLocation(requestParameters: NodesApiRequestLocationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.requestLocationRaw(requestParameters, initOverrides);
    }

}
