/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetAuthTokenViaFsid403Response,
  GetResourcePackages200Response,
  InlineObject,
  ResourcePackage,
} from '../models/index';
import {
    GetAuthTokenViaFsid403ResponseFromJSON,
    GetAuthTokenViaFsid403ResponseToJSON,
    GetResourcePackages200ResponseFromJSON,
    GetResourcePackages200ResponseToJSON,
    InlineObjectFromJSON,
    InlineObjectToJSON,
    ResourcePackageFromJSON,
    ResourcePackageToJSON,
} from '../models/index';

export interface ResourcePackageApiGetResourcePackageByIdRequest {
    resourcePackage: number;
}

export interface ResourcePackageApiGetResourcePackagesRequest {
    perPage?: number;
    page?: number;
    sort?: Array<GetResourcePackagesSortEnum>;
    filterId?: number;
    filterName?: string;
    filterNamePartial?: string;
    filterSlug?: string;
    filterType?: string;
    filterCpuLimit?: number;
    filterMemoryLimitMiB?: number;
}

/**
 * 
 */
export class ResourcePackageApi extends runtime.BaseAPI {

    /**
     * Show a specified resource package
     */
    async getResourcePackageByIdRaw(requestParameters: ResourcePackageApiGetResourcePackageByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResourcePackage>> {
        if (requestParameters['resourcePackage'] == null) {
            throw new runtime.RequiredError(
                'resourcePackage',
                'Required parameter "resourcePackage" was null or undefined when calling getResourcePackageById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/resource-packages/{resourcePackage}`;
        urlPath = urlPath.replace(`{${"resourcePackage"}}`, encodeURIComponent(String(requestParameters['resourcePackage'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResourcePackageFromJSON(jsonValue));
    }

    /**
     * Show a specified resource package
     */
    async getResourcePackageById(requestParameters: ResourcePackageApiGetResourcePackageByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResourcePackage> {
        const response = await this.getResourcePackageByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Show all available resource packages
     */
    async getResourcePackagesRaw(requestParameters: ResourcePackageApiGetResourcePackagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetResourcePackages200Response>> {
        const queryParameters: any = {};

        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }

        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }

        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }

        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }

        if (requestParameters['filterSlug'] != null) {
            queryParameters['filter[slug]'] = requestParameters['filterSlug'];
        }

        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }

        if (requestParameters['filterCpuLimit'] != null) {
            queryParameters['filter[cpuLimit]'] = requestParameters['filterCpuLimit'];
        }

        if (requestParameters['filterMemoryLimitMiB'] != null) {
            queryParameters['filter[memoryLimitMiB]'] = requestParameters['filterMemoryLimitMiB'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/resource-packages`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetResourcePackages200ResponseFromJSON(jsonValue));
    }

    /**
     * Show all available resource packages
     */
    async getResourcePackages(requestParameters: ResourcePackageApiGetResourcePackagesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetResourcePackages200Response> {
        const response = await this.getResourcePackagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetResourcePackagesSortEnum = {
    Id: '-id',
    Id2: 'id',
    Name: '-name',
    Name2: 'name',
    Slug: '-slug',
    Slug2: 'slug',
    Type: '-type',
    Type2: 'type',
    CpuLimit: '-cpuLimit',
    CpuLimit2: 'cpuLimit',
    MemoryLimitMiB: '-memoryLimitMiB',
    MemoryLimitMiB2: 'memoryLimitMiB'
} as const;
export type GetResourcePackagesSortEnum = typeof GetResourcePackagesSortEnum[keyof typeof GetResourcePackagesSortEnum];
