/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InlineObject,
  InlineObject1,
  OperatingSystem,
  SteamBranch,
  SteamLauncher,
} from '../models/index';
import {
    InlineObjectFromJSON,
    InlineObjectToJSON,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
    OperatingSystemFromJSON,
    OperatingSystemToJSON,
    SteamBranchFromJSON,
    SteamBranchToJSON,
    SteamLauncherFromJSON,
    SteamLauncherToJSON,
} from '../models/index';

export interface SteamGetBranchesRequest {
    appId: number;
}

export interface SteamGetLauncherRequest {
    appId: number;
    os?: OperatingSystem;
}

/**
 * 
 */
export class SteamApi extends runtime.BaseAPI {

    /**
     * Get branches for a specific steamworks app ID
     */
    async steamGetBranchesRaw(requestParameters: SteamGetBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SteamBranch>>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling steamGetBranches().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['appId'] != null) {
            queryParameters['appId'] = requestParameters['appId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/steam/branches`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SteamBranchFromJSON));
    }

    /**
     * Get branches for a specific steamworks app ID
     */
    async steamGetBranches(requestParameters: SteamGetBranchesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SteamBranch>> {
        const response = await this.steamGetBranchesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get launchers for a specific steamworks app ID, optionally filtered by OS
     */
    async steamGetLauncherRaw(requestParameters: SteamGetLauncherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<SteamLauncher>>> {
        if (requestParameters['appId'] == null) {
            throw new runtime.RequiredError(
                'appId',
                'Required parameter "appId" was null or undefined when calling steamGetLauncher().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['appId'] != null) {
            queryParameters['appId'] = requestParameters['appId'];
        }

        if (requestParameters['os'] != null) {
            queryParameters['os'] = requestParameters['os'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/v1/binaries/steam/launchers`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(SteamLauncherFromJSON));
    }

    /**
     * Get launchers for a specific steamworks app ID, optionally filtered by OS
     */
    async steamGetLauncher(requestParameters: SteamGetLauncherRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<SteamLauncher>> {
        const response = await this.steamGetLauncherRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
