/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppLocationSettingStatus = {
    Pending: 'pending',
    Creating: 'creating',
    Updating: 'updating',
    Deleting: 'deleting',
    Upscaling: 'upscaling',
    Downscaling: 'downscaling',
    Error: 'error',
    Ready: 'ready',
    Waiting: 'waiting',
    Moving: 'moving',
    Cloning: 'cloning'
} as const;
export type AppLocationSettingStatus = typeof AppLocationSettingStatus[keyof typeof AppLocationSettingStatus];


export function instanceOfAppLocationSettingStatus(value: any): boolean {
    for (const key in AppLocationSettingStatus) {
        if (Object.prototype.hasOwnProperty.call(AppLocationSettingStatus, key)) {
            if (AppLocationSettingStatus[key as keyof typeof AppLocationSettingStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppLocationSettingStatusFromJSON(json: any): AppLocationSettingStatus {
    return AppLocationSettingStatusFromJSONTyped(json, false);
}

export function AppLocationSettingStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppLocationSettingStatus {
    return json as AppLocationSettingStatus;
}

export function AppLocationSettingStatusToJSON(value?: AppLocationSettingStatus | null): any {
    return value as any;
}

export function AppLocationSettingStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AppLocationSettingStatus {
    return value as AppLocationSettingStatus;
}

