/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerConfig } from './ServerConfig';
import {
    ServerConfigFromJSON,
    ServerConfigFromJSONTyped,
    ServerConfigToJSON,
    ServerConfigToJSONTyped,
} from './ServerConfig';
import type { Placement } from './Placement';
import {
    PlacementFromJSON,
    PlacementFromJSONTyped,
    PlacementToJSON,
    PlacementToJSONTyped,
} from './Placement';
import type { AppLocationSettingStatus } from './AppLocationSettingStatus';
import {
    AppLocationSettingStatusFromJSON,
    AppLocationSettingStatusFromJSONTyped,
    AppLocationSettingStatusToJSON,
    AppLocationSettingStatusToJSONTyped,
} from './AppLocationSettingStatus';

/**
 * 
 * @export
 * @interface AppLocationSetting
 */
export interface AppLocationSetting {
    /**
     * The id of the app location setting
     * @type {number}
     * @memberof AppLocationSetting
     */
    id: number;
    /**
     * The name of the app location setting
     * @type {string}
     * @memberof AppLocationSetting
     */
    name: string;
    /**
     * The app id of the app location setting
     * @type {number}
     * @memberof AppLocationSetting
     */
    appId: number;
    /**
     * The server config id of the app location setting
     * @type {number}
     * @memberof AppLocationSetting
     */
    serverConfigId: number;
    /**
     * The number of instances that should run at the specific location
     * @type {number}
     * @memberof AppLocationSetting
     */
    numInstances: number;
    /**
     * Whether the auto scaler is enabled
     * @type {boolean}
     * @memberof AppLocationSetting
     */
    autoScalerEnabled: boolean;
    /**
     * The minimum number of instances that should run at the specific location
     * @type {number}
     * @memberof AppLocationSetting
     */
    autoScalerMin?: number;
    /**
     * The maximum number of instances that should run at the specific location
     * @type {number}
     * @memberof AppLocationSetting
     */
    autoScalerMax?: number;
    /**
     * The current status
     * @type {AppLocationSettingStatus}
     * @memberof AppLocationSetting
     */
    status: AppLocationSettingStatus;
    /**
     * An optional message
     * @type {string}
     * @memberof AppLocationSetting
     */
    statusMessage: string | null;
    /**
     * Indicates if the app location setting is under maintenance
     * @type {boolean}
     * @memberof AppLocationSetting
     */
    maintenance: boolean;
    /**
     * Indicates whether the app location setting is currently in use
     * @type {boolean}
     * @memberof AppLocationSetting
     */
    inUse: boolean;
    /**
     * The placement to use
     * @type {Placement}
     * @memberof AppLocationSetting
     */
    placement: Placement;
    /**
     * The server config to use
     * @type {ServerConfig}
     * @memberof AppLocationSetting
     */
    serverConfig?: ServerConfig;
}



/**
 * Check if a given object implements the AppLocationSetting interface.
 */
export function instanceOfAppLocationSetting(value: object): value is AppLocationSetting {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('serverConfigId' in value) || value['serverConfigId'] === undefined) return false;
    if (!('numInstances' in value) || value['numInstances'] === undefined) return false;
    if (!('autoScalerEnabled' in value) || value['autoScalerEnabled'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusMessage' in value) || value['statusMessage'] === undefined) return false;
    if (!('maintenance' in value) || value['maintenance'] === undefined) return false;
    if (!('inUse' in value) || value['inUse'] === undefined) return false;
    if (!('placement' in value) || value['placement'] === undefined) return false;
    return true;
}

export function AppLocationSettingFromJSON(json: any): AppLocationSetting {
    return AppLocationSettingFromJSONTyped(json, false);
}

export function AppLocationSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppLocationSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'appId': json['appId'],
        'serverConfigId': json['serverConfigId'],
        'numInstances': json['numInstances'],
        'autoScalerEnabled': json['autoScalerEnabled'],
        'autoScalerMin': json['autoScalerMin'] == null ? undefined : json['autoScalerMin'],
        'autoScalerMax': json['autoScalerMax'] == null ? undefined : json['autoScalerMax'],
        'status': AppLocationSettingStatusFromJSON(json['status']),
        'statusMessage': json['statusMessage'],
        'maintenance': json['maintenance'],
        'inUse': json['inUse'],
        'placement': PlacementFromJSON(json['placement']),
        'serverConfig': json['serverConfig'] == null ? undefined : ServerConfigFromJSON(json['serverConfig']),
    };
}

export function AppLocationSettingToJSON(json: any): AppLocationSetting {
    return AppLocationSettingToJSONTyped(json, false);
}

export function AppLocationSettingToJSONTyped(value?: AppLocationSetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'appId': value['appId'],
        'serverConfigId': value['serverConfigId'],
        'numInstances': value['numInstances'],
        'autoScalerEnabled': value['autoScalerEnabled'],
        'autoScalerMin': value['autoScalerMin'],
        'autoScalerMax': value['autoScalerMax'],
        'status': AppLocationSettingStatusToJSON(value['status']),
        'statusMessage': value['statusMessage'],
        'maintenance': value['maintenance'],
        'inUse': value['inUse'],
        'placement': PlacementToJSON(value['placement']),
        'serverConfig': ServerConfigToJSON(value['serverConfig']),
    };
}

