/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const AppStatus = {
    Ready: 'ready',
    Updating: 'updating',
    Deleting: 'deleting',
    Error: 'error',
    Waiting: 'waiting'
} as const;
export type AppStatus = typeof AppStatus[keyof typeof AppStatus];


export function instanceOfAppStatus(value: any): boolean {
    for (const key in AppStatus) {
        if (Object.prototype.hasOwnProperty.call(AppStatus, key)) {
            if (AppStatus[key as keyof typeof AppStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AppStatusFromJSON(json: any): AppStatus {
    return AppStatusFromJSONTyped(json, false);
}

export function AppStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppStatus {
    return json as AppStatus;
}

export function AppStatusToJSON(value?: AppStatus | null): any {
    return value as any;
}

export function AppStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AppStatus {
    return value as AppStatus;
}

