/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Architecture = {
    X8664: 'x86_64'
} as const;
export type Architecture = typeof Architecture[keyof typeof Architecture];


export function instanceOfArchitecture(value: any): boolean {
    for (const key in Architecture) {
        if (Object.prototype.hasOwnProperty.call(Architecture, key)) {
            if (Architecture[key as keyof typeof Architecture] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ArchitectureFromJSON(json: any): Architecture {
    return ArchitectureFromJSONTyped(json, false);
}

export function ArchitectureFromJSONTyped(json: any, ignoreDiscriminator: boolean): Architecture {
    return json as Architecture;
}

export function ArchitectureToJSON(value?: Architecture | null): any {
    return value as any;
}

export function ArchitectureToJSONTyped(value: any, ignoreDiscriminator: boolean): Architecture {
    return value as Architecture;
}

