/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Auth
 */
export interface Auth {
    /**
     * The authentication token, which must be used as a Bearer token in subsequent requests.
     * @type {string}
     * @memberof Auth
     */
    token: string;
}

/**
 * Check if a given object implements the Auth interface.
 */
export function instanceOfAuth(value: object): value is Auth {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function AuthFromJSON(json: any): Auth {
    return AuthFromJSONTyped(json, false);
}

export function AuthFromJSONTyped(json: any, ignoreDiscriminator: boolean): Auth {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function AuthToJSON(json: any): Auth {
    return AuthToJSONTyped(json, false);
}

export function AuthToJSONTyped(value?: Auth | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

