/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Backup
 */
export interface Backup {
    /**
     * The name of the backup
     * @type {string}
     * @memberof Backup
     */
    name: string;
    /**
     * The name of the stored archive
     * @type {string}
     * @memberof Backup
     */
    archiveName: string;
    /**
     * The timestamp of the backups creation
     * @type {Date}
     * @memberof Backup
     */
    createdAt: Date;
    /**
     * The timestamp of when the backup was restored, null if not restored
     * @type {Date}
     * @memberof Backup
     */
    restoredAt: Date | null;
}

/**
 * Check if a given object implements the Backup interface.
 */
export function instanceOfBackup(value: object): value is Backup {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('archiveName' in value) || value['archiveName'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('restoredAt' in value) || value['restoredAt'] === undefined) return false;
    return true;
}

export function BackupFromJSON(json: any): Backup {
    return BackupFromJSONTyped(json, false);
}

export function BackupFromJSONTyped(json: any, ignoreDiscriminator: boolean): Backup {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'archiveName': json['archiveName'],
        'createdAt': (new Date(json['createdAt'])),
        'restoredAt': (json['restoredAt'] == null ? null : new Date(json['restoredAt'])),
    };
}

export function BackupToJSON(json: any): Backup {
    return BackupToJSONTyped(json, false);
}

export function BackupToJSONTyped(value?: Backup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'archiveName': value['archiveName'],
        'createdAt': value['createdAt'].toISOString(),
        'restoredAt': value['restoredAt'] == null ? value['restoredAt'] : value['restoredAt'].toISOString(),
    };
}

