/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const BinaryStatus = {
    Pending: 'pending',
    Building: 'building',
    Deleting: 'deleting',
    Updating: 'updating',
    Waiting: 'waiting',
    Error: 'error',
    Ready: 'ready'
} as const;
export type BinaryStatus = typeof BinaryStatus[keyof typeof BinaryStatus];


export function instanceOfBinaryStatus(value: any): boolean {
    for (const key in BinaryStatus) {
        if (Object.prototype.hasOwnProperty.call(BinaryStatus, key)) {
            if (BinaryStatus[key as keyof typeof BinaryStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BinaryStatusFromJSON(json: any): BinaryStatus {
    return BinaryStatusFromJSONTyped(json, false);
}

export function BinaryStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinaryStatus {
    return json as BinaryStatus;
}

export function BinaryStatusToJSON(value?: BinaryStatus | null): any {
    return value as any;
}

export function BinaryStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): BinaryStatus {
    return value as BinaryStatus;
}

