/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperatingSystem } from './OperatingSystem';
import {
    OperatingSystemFromJSON,
    OperatingSystemFromJSONTyped,
    OperatingSystemToJSON,
    OperatingSystemToJSONTyped,
} from './OperatingSystem';
import type { BinaryStatus } from './BinaryStatus';
import {
    BinaryStatusFromJSON,
    BinaryStatusFromJSONTyped,
    BinaryStatusToJSON,
    BinaryStatusToJSONTyped,
} from './BinaryStatus';
import type { BinaryType } from './BinaryType';
import {
    BinaryTypeFromJSON,
    BinaryTypeFromJSONTyped,
    BinaryTypeToJSON,
    BinaryTypeToJSONTyped,
} from './BinaryType';
import type { Steam } from './Steam';
import {
    SteamFromJSON,
    SteamFromJSONTyped,
    SteamToJSON,
    SteamToJSONTyped,
} from './Steam';
import type { DockerImage } from './DockerImage';
import {
    DockerImageFromJSON,
    DockerImageFromJSONTyped,
    DockerImageToJSON,
    DockerImageToJSONTyped,
} from './DockerImage';

/**
 * 
 * @export
 * @interface Binary
 */
export interface Binary {
    /**
     * The id of the binary
     * @type {number}
     * @memberof Binary
     */
    id: number;
    /**
     * The app id of the binary
     * @type {number}
     * @memberof Binary
     */
    appId: number;
    /**
     * The app id of the binary
     * @type {string}
     * @memberof Binary
     */
    name: string;
    /**
     * The version of the binary
     * @type {string}
     * @memberof Binary
     */
    version: string;
    /**
     * The type of the binary
     * @type {BinaryType}
     * @memberof Binary
     */
    type: BinaryType;
    /**
     * The operating system of the binary
     * @type {OperatingSystem}
     * @memberof Binary
     */
    os: OperatingSystem;
    /**
     * Indicates if the binary is under maintenance
     * @type {boolean}
     * @memberof Binary
     */
    maintenance: boolean;
    /**
     * The current status of the binary
     * @type {BinaryStatus}
     * @memberof Binary
     */
    status: BinaryStatus;
    /**
     * An optional message returned by the build process
     * @type {string}
     * @memberof Binary
     */
    statusMessage: string | null;
    /**
     * The current progress percentage of the image build (0-100). Only present for binaries of type steam.
     * @type {number}
     * @memberof Binary
     */
    progress?: number | null;
    /**
     * A message describing the current build step. Only present for binaries of type steam.
     * @type {string}
     * @memberof Binary
     */
    progressMessage?: string | null;
    /**
     * Indicates whether the binary is currently in use
     * @type {boolean}
     * @memberof Binary
     */
    inUse: boolean;
    /**
     * The docker image of the binary
     * @type {DockerImage}
     * @memberof Binary
     */
    dockerImage?: DockerImage;
    /**
     * The steam of the binary
     * @type {Steam}
     * @memberof Binary
     */
    steam?: Steam;
}



/**
 * Check if a given object implements the Binary interface.
 */
export function instanceOfBinary(value: object): value is Binary {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    if (!('maintenance' in value) || value['maintenance'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusMessage' in value) || value['statusMessage'] === undefined) return false;
    if (!('inUse' in value) || value['inUse'] === undefined) return false;
    return true;
}

export function BinaryFromJSON(json: any): Binary {
    return BinaryFromJSONTyped(json, false);
}

export function BinaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Binary {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appId': json['appId'],
        'name': json['name'],
        'version': json['version'],
        'type': BinaryTypeFromJSON(json['type']),
        'os': OperatingSystemFromJSON(json['os']),
        'maintenance': json['maintenance'],
        'status': BinaryStatusFromJSON(json['status']),
        'statusMessage': json['statusMessage'],
        'progress': json['progress'] == null ? undefined : json['progress'],
        'progressMessage': json['progressMessage'] == null ? undefined : json['progressMessage'],
        'inUse': json['inUse'],
        'dockerImage': json['dockerImage'] == null ? undefined : DockerImageFromJSON(json['dockerImage']),
        'steam': json['steam'] == null ? undefined : SteamFromJSON(json['steam']),
    };
}

export function BinaryToJSON(json: any): Binary {
    return BinaryToJSONTyped(json, false);
}

export function BinaryToJSONTyped(value?: Binary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'appId': value['appId'],
        'name': value['name'],
        'version': value['version'],
        'type': BinaryTypeToJSON(value['type']),
        'os': OperatingSystemToJSON(value['os']),
        'maintenance': value['maintenance'],
        'status': BinaryStatusToJSON(value['status']),
        'statusMessage': value['statusMessage'],
        'progress': value['progress'],
        'progressMessage': value['progressMessage'],
        'inUse': value['inUse'],
        'dockerImage': DockerImageToJSON(value['dockerImage']),
        'steam': SteamToJSON(value['steam']),
    };
}

