/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface CreateUpdatePlacement
 */
export interface CreateUpdatePlacement {
    /**
     * The constraints to use
     * @type {Location}
     * @memberof CreateUpdatePlacement
     */
    constraints: Location;
}

/**
 * Check if a given object implements the CreateUpdatePlacement interface.
 */
export function instanceOfCreateUpdatePlacement(value: object): value is CreateUpdatePlacement {
    if (!('constraints' in value) || value['constraints'] === undefined) return false;
    return true;
}

export function CreateUpdatePlacementFromJSON(json: any): CreateUpdatePlacement {
    return CreateUpdatePlacementFromJSONTyped(json, false);
}

export function CreateUpdatePlacementFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUpdatePlacement {
    if (json == null) {
        return json;
    }
    return {
        
        'constraints': LocationFromJSON(json['constraints']),
    };
}

export function CreateUpdatePlacementToJSON(json: any): CreateUpdatePlacement {
    return CreateUpdatePlacementToJSONTyped(json, false);
}

export function CreateUpdatePlacementToJSONTyped(value?: CreateUpdatePlacement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'constraints': LocationToJSON(value['constraints']),
    };
}

