/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DockerImage
 */
export interface DockerImage {
    /**
     * The name of the docker image
     * @type {string}
     * @memberof DockerImage
     */
    imageName: string;
    /**
     * The id of the registry to load the image
     * @type {number}
     * @memberof DockerImage
     */
    registryId: number;
    /**
     * Indicates whether the docker image is currently in use
     * @type {boolean}
     * @memberof DockerImage
     */
    inUse: boolean;
}

/**
 * Check if a given object implements the DockerImage interface.
 */
export function instanceOfDockerImage(value: object): value is DockerImage {
    if (!('imageName' in value) || value['imageName'] === undefined) return false;
    if (!('registryId' in value) || value['registryId'] === undefined) return false;
    if (!('inUse' in value) || value['inUse'] === undefined) return false;
    return true;
}

export function DockerImageFromJSON(json: any): DockerImage {
    return DockerImageFromJSONTyped(json, false);
}

export function DockerImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerImage {
    if (json == null) {
        return json;
    }
    return {
        
        'imageName': json['imageName'],
        'registryId': json['registryId'],
        'inUse': json['inUse'],
    };
}

export function DockerImageToJSON(json: any): DockerImage {
    return DockerImageToJSONTyped(json, false);
}

export function DockerImageToJSONTyped(value?: DockerImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'imageName': value['imageName'],
        'registryId': value['registryId'],
        'inUse': value['inUse'],
    };
}

