/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const DockerRegistryType = {
    Default: 'default',
    Gitlab: 'gitlab',
    Github: 'github',
    Custom: 'custom',
    Dockerhub: 'dockerhub',
    Azure: 'azure',
    Awsecr: 'awsecr',
    Other: 'other'
} as const;
export type DockerRegistryType = typeof DockerRegistryType[keyof typeof DockerRegistryType];


export function instanceOfDockerRegistryType(value: any): boolean {
    for (const key in DockerRegistryType) {
        if (Object.prototype.hasOwnProperty.call(DockerRegistryType, key)) {
            if (DockerRegistryType[key as keyof typeof DockerRegistryType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DockerRegistryTypeFromJSON(json: any): DockerRegistryType {
    return DockerRegistryTypeFromJSONTyped(json, false);
}

export function DockerRegistryTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DockerRegistryType {
    return json as DockerRegistryType;
}

export function DockerRegistryTypeToJSON(value?: DockerRegistryType | null): any {
    return value as any;
}

export function DockerRegistryTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): DockerRegistryType {
    return value as DockerRegistryType;
}

