/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ResourcePackage } from './ResourcePackage';
import {
    ResourcePackageFromJSON,
    ResourcePackageFromJSONTyped,
    ResourcePackageToJSON,
    ResourcePackageToJSONTyped,
} from './ResourcePackage';
import type { GetAppLocationSettings200ResponseLinks } from './GetAppLocationSettings200ResponseLinks';
import {
    GetAppLocationSettings200ResponseLinksFromJSON,
    GetAppLocationSettings200ResponseLinksFromJSONTyped,
    GetAppLocationSettings200ResponseLinksToJSON,
    GetAppLocationSettings200ResponseLinksToJSONTyped,
} from './GetAppLocationSettings200ResponseLinks';
import type { GetAppLocationSettings200ResponseMeta } from './GetAppLocationSettings200ResponseMeta';
import {
    GetAppLocationSettings200ResponseMetaFromJSON,
    GetAppLocationSettings200ResponseMetaFromJSONTyped,
    GetAppLocationSettings200ResponseMetaToJSON,
    GetAppLocationSettings200ResponseMetaToJSONTyped,
} from './GetAppLocationSettings200ResponseMeta';

/**
 * 
 * @export
 * @interface GetResourcePackages200Response
 */
export interface GetResourcePackages200Response {
    /**
     * 
     * @type {Array<ResourcePackage>}
     * @memberof GetResourcePackages200Response
     */
    data: Array<ResourcePackage>;
    /**
     * 
     * @type {GetAppLocationSettings200ResponseLinks}
     * @memberof GetResourcePackages200Response
     */
    links: GetAppLocationSettings200ResponseLinks;
    /**
     * 
     * @type {GetAppLocationSettings200ResponseMeta}
     * @memberof GetResourcePackages200Response
     */
    meta: GetAppLocationSettings200ResponseMeta;
}

/**
 * Check if a given object implements the GetResourcePackages200Response interface.
 */
export function instanceOfGetResourcePackages200Response(value: object): value is GetResourcePackages200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetResourcePackages200ResponseFromJSON(json: any): GetResourcePackages200Response {
    return GetResourcePackages200ResponseFromJSONTyped(json, false);
}

export function GetResourcePackages200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetResourcePackages200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ResourcePackageFromJSON)),
        'links': GetAppLocationSettings200ResponseLinksFromJSON(json['links']),
        'meta': GetAppLocationSettings200ResponseMetaFromJSON(json['meta']),
    };
}

export function GetResourcePackages200ResponseToJSON(json: any): GetResourcePackages200Response {
    return GetResourcePackages200ResponseToJSONTyped(json, false);
}

export function GetResourcePackages200ResponseToJSONTyped(value?: GetResourcePackages200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ResourcePackageToJSON)),
        'links': GetAppLocationSettings200ResponseLinksToJSON(value['links']),
        'meta': GetAppLocationSettings200ResponseMetaToJSON(value['meta']),
    };
}

