/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServerConfig } from './ServerConfig';
import {
    ServerConfigFromJSON,
    ServerConfigFromJSONTyped,
    ServerConfigToJSON,
    ServerConfigToJSONTyped,
} from './ServerConfig';
import type { GetAppLocationSettings200ResponseLinks } from './GetAppLocationSettings200ResponseLinks';
import {
    GetAppLocationSettings200ResponseLinksFromJSON,
    GetAppLocationSettings200ResponseLinksFromJSONTyped,
    GetAppLocationSettings200ResponseLinksToJSON,
    GetAppLocationSettings200ResponseLinksToJSONTyped,
} from './GetAppLocationSettings200ResponseLinks';
import type { GetAppLocationSettings200ResponseMeta } from './GetAppLocationSettings200ResponseMeta';
import {
    GetAppLocationSettings200ResponseMetaFromJSON,
    GetAppLocationSettings200ResponseMetaFromJSONTyped,
    GetAppLocationSettings200ResponseMetaToJSON,
    GetAppLocationSettings200ResponseMetaToJSONTyped,
} from './GetAppLocationSettings200ResponseMeta';

/**
 * 
 * @export
 * @interface GetServerConfigs200Response
 */
export interface GetServerConfigs200Response {
    /**
     * 
     * @type {Array<ServerConfig>}
     * @memberof GetServerConfigs200Response
     */
    data: Array<ServerConfig>;
    /**
     * 
     * @type {GetAppLocationSettings200ResponseLinks}
     * @memberof GetServerConfigs200Response
     */
    links: GetAppLocationSettings200ResponseLinks;
    /**
     * 
     * @type {GetAppLocationSettings200ResponseMeta}
     * @memberof GetServerConfigs200Response
     */
    meta: GetAppLocationSettings200ResponseMeta;
}

/**
 * Check if a given object implements the GetServerConfigs200Response interface.
 */
export function instanceOfGetServerConfigs200Response(value: object): value is GetServerConfigs200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('links' in value) || value['links'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function GetServerConfigs200ResponseFromJSON(json: any): GetServerConfigs200Response {
    return GetServerConfigs200ResponseFromJSONTyped(json, false);
}

export function GetServerConfigs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetServerConfigs200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ServerConfigFromJSON)),
        'links': GetAppLocationSettings200ResponseLinksFromJSON(json['links']),
        'meta': GetAppLocationSettings200ResponseMetaFromJSON(json['meta']),
    };
}

export function GetServerConfigs200ResponseToJSON(json: any): GetServerConfigs200Response {
    return GetServerConfigs200ResponseToJSONTyped(json, false);
}

export function GetServerConfigs200ResponseToJSONTyped(value?: GetServerConfigs200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(ServerConfigToJSON)),
        'links': GetAppLocationSettings200ResponseLinksToJSON(value['links']),
        'meta': GetAppLocationSettings200ResponseMetaToJSON(value['meta']),
    };
}

