/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetricTimeResult
 */
export interface MetricTimeResult {
    /**
     * Labels identifying this time series.
     * @type {{ [key: string]: string; }}
     * @memberof MetricTimeResult
     */
    metric: { [key: string]: string; };
    /**
     * List of [timestamp, value] pairs for this series.
     * @type {Array<Array<any>>}
     * @memberof MetricTimeResult
     */
    values: Array<Array<any>>;
}

/**
 * Check if a given object implements the MetricTimeResult interface.
 */
export function instanceOfMetricTimeResult(value: object): value is MetricTimeResult {
    if (!('metric' in value) || value['metric'] === undefined) return false;
    if (!('values' in value) || value['values'] === undefined) return false;
    return true;
}

export function MetricTimeResultFromJSON(json: any): MetricTimeResult {
    return MetricTimeResultFromJSONTyped(json, false);
}

export function MetricTimeResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricTimeResult {
    if (json == null) {
        return json;
    }
    return {
        
        'metric': json['metric'],
        'values': json['values'],
    };
}

export function MetricTimeResultToJSON(json: any): MetricTimeResult {
    return MetricTimeResultToJSONTyped(json, false);
}

export function MetricTimeResultToJSONTyped(value?: MetricTimeResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metric': value['metric'],
        'values': value['values'],
    };
}

