/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Mount
 */
export interface Mount {
    /**
     * The path in the container
     * @type {string}
     * @memberof Mount
     */
    target: string;
    /**
     * Whether this mount point is read only
     * @type {boolean}
     * @memberof Mount
     */
    readOnly: boolean;
}

/**
 * Check if a given object implements the Mount interface.
 */
export function instanceOfMount(value: object): value is Mount {
    if (!('target' in value) || value['target'] === undefined) return false;
    if (!('readOnly' in value) || value['readOnly'] === undefined) return false;
    return true;
}

export function MountFromJSON(json: any): Mount {
    return MountFromJSONTyped(json, false);
}

export function MountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Mount {
    if (json == null) {
        return json;
    }
    return {
        
        'target': json['target'],
        'readOnly': json['readOnly'],
    };
}

export function MountToJSON(json: any): Mount {
    return MountToJSONTyped(json, false);
}

export function MountToJSONTyped(value?: Mount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target': value['target'],
        'readOnly': value['readOnly'],
    };
}

