/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OperatingSystem } from './OperatingSystem';
import {
    OperatingSystemFromJSON,
    OperatingSystemFromJSONTyped,
    OperatingSystemToJSON,
    OperatingSystemToJSONTyped,
} from './OperatingSystem';
import type { Architecture } from './Architecture';
import {
    ArchitectureFromJSON,
    ArchitectureFromJSONTyped,
    ArchitectureToJSON,
    ArchitectureToJSONTyped,
} from './Architecture';

/**
 * 
 * @export
 * @interface Node
 */
export interface Node {
    /**
     * The architecture of the node (e.g., 'x86_64')
     * @type {Architecture}
     * @memberof Node
     */
    architecture: Architecture;
    /**
     * The operating system of the node
     * @type {OperatingSystem}
     * @memberof Node
     */
    os: OperatingSystem;
    /**
     * The IP address of the node
     * @type {string}
     * @memberof Node
     */
    address: string;
}



/**
 * Check if a given object implements the Node interface.
 */
export function instanceOfNode(value: object): value is Node {
    if (!('architecture' in value) || value['architecture'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    if (!('address' in value) || value['address'] === undefined) return false;
    return true;
}

export function NodeFromJSON(json: any): Node {
    return NodeFromJSONTyped(json, false);
}

export function NodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Node {
    if (json == null) {
        return json;
    }
    return {
        
        'architecture': ArchitectureFromJSON(json['architecture']),
        'os': OperatingSystemFromJSON(json['os']),
        'address': json['address'],
    };
}

export function NodeToJSON(json: any): Node {
    return NodeToJSONTyped(json, false);
}

export function NodeToJSONTyped(value?: Node | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'architecture': ArchitectureToJSON(value['architecture']),
        'os': OperatingSystemToJSON(value['os']),
        'address': value['address'],
    };
}

