/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OperatingSystem = {
    Windows: 'windows',
    Linux: 'linux'
} as const;
export type OperatingSystem = typeof OperatingSystem[keyof typeof OperatingSystem];


export function instanceOfOperatingSystem(value: any): boolean {
    for (const key in OperatingSystem) {
        if (Object.prototype.hasOwnProperty.call(OperatingSystem, key)) {
            if (OperatingSystem[key as keyof typeof OperatingSystem] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OperatingSystemFromJSON(json: any): OperatingSystem {
    return OperatingSystemFromJSONTyped(json, false);
}

export function OperatingSystemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OperatingSystem {
    return json as OperatingSystem;
}

export function OperatingSystemToJSON(value?: OperatingSystem | null): any {
    return value as any;
}

export function OperatingSystemToJSONTyped(value: any, ignoreDiscriminator: boolean): OperatingSystem {
    return value as OperatingSystem;
}

