/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchMetadataRequest
 */
export interface PatchMetadataRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof PatchMetadataRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the PatchMetadataRequest interface.
 */
export function instanceOfPatchMetadataRequest(value: object): value is PatchMetadataRequest {
    return true;
}

export function PatchMetadataRequestFromJSON(json: any): PatchMetadataRequest {
    return PatchMetadataRequestFromJSONTyped(json, false);
}

export function PatchMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function PatchMetadataRequestToJSON(json: any): PatchMetadataRequest {
    return PatchMetadataRequestToJSONTyped(json, false);
}

export function PatchMetadataRequestToJSONTyped(value?: PatchMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
    };
}

