/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DnsMode } from './DnsMode';
import {
    DnsModeFromJSON,
    DnsModeFromJSONTyped,
    DnsModeToJSON,
    DnsModeToJSONTyped,
} from './DnsMode';
import type { Protocol } from './Protocol';
import {
    ProtocolFromJSON,
    ProtocolFromJSONTyped,
    ProtocolToJSON,
    ProtocolToJSONTyped,
} from './Protocol';

/**
 * 
 * @export
 * @interface Port
 */
export interface Port {
    /**
     * The name for the port.
     * @type {string}
     * @memberof Port
     */
    name: string;
    /**
     * The protocol used by the port.
     * @type {Protocol}
     * @memberof Port
     */
    protocol: Protocol;
    /**
     * The port inside the container. Incoming traffic is routed to this port within the container.
     * @type {number}
     * @memberof Port
     */
    targetPort: number;
    /**
     * The externally published port, which allows external access. If `null`, the port has not yet been assigned.
     * @type {number}
     * @memberof Port
     */
    publishedPort: number | null;
    /**
     * DNS mode of the port
     * @type {DnsMode}
     * @memberof Port
     */
    dnsMode: DnsMode | null;
    /**
     * Indicates if the port should be private (not publicly published)
     * @type {boolean}
     * @memberof Port
     */
    dnsPrivate: boolean;
    /**
     * Public URL over http
     * @type {string}
     * @memberof Port
     */
    dnsHttp: string | null;
    /**
     * Public URL over https
     * @type {string}
     * @memberof Port
     */
    dnsHttps: string | null;
}



/**
 * Check if a given object implements the Port interface.
 */
export function instanceOfPort(value: object): value is Port {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('protocol' in value) || value['protocol'] === undefined) return false;
    if (!('targetPort' in value) || value['targetPort'] === undefined) return false;
    if (!('publishedPort' in value) || value['publishedPort'] === undefined) return false;
    if (!('dnsMode' in value) || value['dnsMode'] === undefined) return false;
    if (!('dnsPrivate' in value) || value['dnsPrivate'] === undefined) return false;
    if (!('dnsHttp' in value) || value['dnsHttp'] === undefined) return false;
    if (!('dnsHttps' in value) || value['dnsHttps'] === undefined) return false;
    return true;
}

export function PortFromJSON(json: any): Port {
    return PortFromJSONTyped(json, false);
}

export function PortFromJSONTyped(json: any, ignoreDiscriminator: boolean): Port {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'protocol': ProtocolFromJSON(json['protocol']),
        'targetPort': json['targetPort'],
        'publishedPort': json['publishedPort'],
        'dnsMode': DnsModeFromJSON(json['dnsMode']),
        'dnsPrivate': json['dnsPrivate'],
        'dnsHttp': json['dnsHttp'],
        'dnsHttps': json['dnsHttps'],
    };
}

export function PortToJSON(json: any): Port {
    return PortToJSONTyped(json, false);
}

export function PortToJSONTyped(value?: Port | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'protocol': ProtocolToJSON(value['protocol']),
        'targetPort': value['targetPort'],
        'publishedPort': value['publishedPort'],
        'dnsMode': DnsModeToJSON(value['dnsMode']),
        'dnsPrivate': value['dnsPrivate'],
        'dnsHttp': value['dnsHttp'],
        'dnsHttps': value['dnsHttps'],
    };
}

