/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const RestartPolicyCondition = {
    None: 'none',
    Any: 'any',
    OnFailure: 'on-failure'
} as const;
export type RestartPolicyCondition = typeof RestartPolicyCondition[keyof typeof RestartPolicyCondition];


export function instanceOfRestartPolicyCondition(value: any): boolean {
    for (const key in RestartPolicyCondition) {
        if (Object.prototype.hasOwnProperty.call(RestartPolicyCondition, key)) {
            if (RestartPolicyCondition[key as keyof typeof RestartPolicyCondition] === value) {
                return true;
            }
        }
    }
    return false;
}

export function RestartPolicyConditionFromJSON(json: any): RestartPolicyCondition {
    return RestartPolicyConditionFromJSONTyped(json, false);
}

export function RestartPolicyConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestartPolicyCondition {
    return json as RestartPolicyCondition;
}

export function RestartPolicyConditionToJSON(value?: RestartPolicyCondition | null): any {
    return value as any;
}

export function RestartPolicyConditionToJSONTyped(value: any, ignoreDiscriminator: boolean): RestartPolicyCondition {
    return value as RestartPolicyCondition;
}

