/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Backup } from './Backup';
import {
    BackupFromJSON,
    BackupFromJSONTyped,
    BackupToJSON,
    BackupToJSONTyped,
} from './Backup';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
    NodeToJSONTyped,
} from './Node';
import type { Port } from './Port';
import {
    PortFromJSON,
    PortFromJSONTyped,
    PortToJSON,
    PortToJSONTyped,
} from './Port';
import type { ResourcePackage } from './ResourcePackage';
import {
    ResourcePackageFromJSON,
    ResourcePackageFromJSONTyped,
    ResourcePackageToJSON,
    ResourcePackageToJSONTyped,
} from './ResourcePackage';
import type { EnvironmentVariable } from './EnvironmentVariable';
import {
    EnvironmentVariableFromJSON,
    EnvironmentVariableFromJSONTyped,
    EnvironmentVariableToJSON,
    EnvironmentVariableToJSONTyped,
} from './EnvironmentVariable';
import type { DockerServiceAutoscaling } from './DockerServiceAutoscaling';
import {
    DockerServiceAutoscalingFromJSON,
    DockerServiceAutoscalingFromJSONTyped,
    DockerServiceAutoscalingToJSON,
    DockerServiceAutoscalingToJSONTyped,
} from './DockerServiceAutoscaling';
import type { RestartPolicy } from './RestartPolicy';
import {
    RestartPolicyFromJSON,
    RestartPolicyFromJSONTyped,
    RestartPolicyToJSON,
    RestartPolicyToJSONTyped,
} from './RestartPolicy';
import type { Location } from './Location';
import {
    LocationFromJSON,
    LocationFromJSONTyped,
    LocationToJSON,
    LocationToJSONTyped,
} from './Location';

/**
 * 
 * @export
 * @interface Server
 */
export interface Server {
    /**
     * The ID of the service
     * @type {number}
     * @memberof Server
     */
    id: number;
    /**
     * The ID of the location setting
     * @type {number}
     * @memberof Server
     */
    appLocationSettingId: number;
    /**
     * The ID of the instance
     * @type {number}
     * @memberof Server
     */
    instance: number;
    /**
     * The ID of the server config
     * @type {number}
     * @memberof Server
     */
    serverConfigId: number;
    /**
     * The name of the server config
     * @type {string}
     * @memberof Server
     */
    serverConfigName: string;
    /**
     * The name of the service
     * @type {string}
     * @memberof Server
     */
    name: string;
    /**
     * The current status
     * @type {string}
     * @memberof Server
     */
    status: string;
    /**
     * An optional message
     * @type {string}
     * @memberof Server
     */
    statusMessage: string | null;
    /**
     * The FQDN of the service
     * @type {string}
     * @memberof Server
     */
    dns: string | null;
    /**
     * Indicates whether the service can be backed up
     * @type {boolean}
     * @memberof Server
     */
    isBackupable: boolean;
    /**
     * Indicates whether the service can be restored
     * @type {boolean}
     * @memberof Server
     */
    isRestorable: boolean;
    /**
     * Indicates whether the service is pending (not running) due to insufficient resources on the node.
     * @type {boolean}
     * @memberof Server
     */
    isPending: boolean;
    /**
     * Indicates whether the service is currently not found/missing in the cluster.
     * @type {boolean}
     * @memberof Server
     */
    isNotFound: boolean;
    /**
     * Indicates whether the service is currently in an overall healthy state.
     * @type {boolean}
     * @memberof Server
     */
    isHealthy: boolean;
    /**
     * Indicates whether the service is currently stopped.
     * @type {boolean}
     * @memberof Server
     */
    isStopped: boolean;
    /**
     * Indicates if the service is under maintenance
     * @type {boolean}
     * @memberof Server
     */
    maintenance: boolean;
    /**
     * The port definitions of the service
     * @type {Array<Port>}
     * @memberof Server
     */
    ports: Array<Port>;
    /**
     * The environment variables of the service
     * @type {{ [key: string]: EnvironmentVariable; }}
     * @memberof Server
     */
    env: { [key: string]: EnvironmentVariable; };
    /**
     * The restart policy of the service
     * @type {RestartPolicy}
     * @memberof Server
     */
    restartPolicy: RestartPolicy;
    /**
     * The assigned node. If missing, it likely means the service is overloaded and has not yet been assigned to any node.
     * @type {Node}
     * @memberof Server
     */
    node?: Node;
    /**
     * The location of the node
     * @type {Location}
     * @memberof Server
     */
    location: Location;
    /**
     * The assigned resource package
     * @type {ResourcePackage}
     * @memberof Server
     */
    resources: ResourcePackage;
    /**
     * The backups of the service
     * @type {Array<Backup>}
     * @memberof Server
     */
    backups: Array<Backup>;
    /**
     * Autoscaling state and health information
     * @type {DockerServiceAutoscaling}
     * @memberof Server
     */
    autoscaling: DockerServiceAutoscaling;
    /**
     * The metadata for the service
     * @type {{ [key: string]: any; }}
     * @memberof Server
     */
    metadata: { [key: string]: any; };
    /**
     * When the service was created
     * @type {Date}
     * @memberof Server
     */
    createdAt: Date | null;
    /**
     * When the service was last updated
     * @type {Date}
     * @memberof Server
     */
    updatedAt: Date | null;
}

/**
 * Check if a given object implements the Server interface.
 */
export function instanceOfServer(value: object): value is Server {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('appLocationSettingId' in value) || value['appLocationSettingId'] === undefined) return false;
    if (!('instance' in value) || value['instance'] === undefined) return false;
    if (!('serverConfigId' in value) || value['serverConfigId'] === undefined) return false;
    if (!('serverConfigName' in value) || value['serverConfigName'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('statusMessage' in value) || value['statusMessage'] === undefined) return false;
    if (!('dns' in value) || value['dns'] === undefined) return false;
    if (!('isBackupable' in value) || value['isBackupable'] === undefined) return false;
    if (!('isRestorable' in value) || value['isRestorable'] === undefined) return false;
    if (!('isPending' in value) || value['isPending'] === undefined) return false;
    if (!('isNotFound' in value) || value['isNotFound'] === undefined) return false;
    if (!('isHealthy' in value) || value['isHealthy'] === undefined) return false;
    if (!('isStopped' in value) || value['isStopped'] === undefined) return false;
    if (!('maintenance' in value) || value['maintenance'] === undefined) return false;
    if (!('ports' in value) || value['ports'] === undefined) return false;
    if (!('env' in value) || value['env'] === undefined) return false;
    if (!('restartPolicy' in value) || value['restartPolicy'] === undefined) return false;
    if (!('location' in value) || value['location'] === undefined) return false;
    if (!('resources' in value) || value['resources'] === undefined) return false;
    if (!('backups' in value) || value['backups'] === undefined) return false;
    if (!('autoscaling' in value) || value['autoscaling'] === undefined) return false;
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ServerFromJSON(json: any): Server {
    return ServerFromJSONTyped(json, false);
}

export function ServerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Server {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'appLocationSettingId': json['appLocationSettingId'],
        'instance': json['instance'],
        'serverConfigId': json['serverConfigId'],
        'serverConfigName': json['serverConfigName'],
        'name': json['name'],
        'status': json['status'],
        'statusMessage': json['status_message'],
        'dns': json['dns'],
        'isBackupable': json['isBackupable'],
        'isRestorable': json['isRestorable'],
        'isPending': json['isPending'],
        'isNotFound': json['isNotFound'],
        'isHealthy': json['isHealthy'],
        'isStopped': json['isStopped'],
        'maintenance': json['maintenance'],
        'ports': ((json['ports'] as Array<any>).map(PortFromJSON)),
        'env': (mapValues(json['env'], EnvironmentVariableFromJSON)),
        'restartPolicy': RestartPolicyFromJSON(json['restartPolicy']),
        'node': json['node'] == null ? undefined : NodeFromJSON(json['node']),
        'location': LocationFromJSON(json['location']),
        'resources': ResourcePackageFromJSON(json['resources']),
        'backups': ((json['backups'] as Array<any>).map(BackupFromJSON)),
        'autoscaling': DockerServiceAutoscalingFromJSON(json['autoscaling']),
        'metadata': json['metadata'],
        'createdAt': (json['createdAt'] == null ? null : new Date(json['createdAt'])),
        'updatedAt': (json['updatedAt'] == null ? null : new Date(json['updatedAt'])),
    };
}

export function ServerToJSON(json: any): Server {
    return ServerToJSONTyped(json, false);
}

export function ServerToJSONTyped(value?: Server | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'appLocationSettingId': value['appLocationSettingId'],
        'instance': value['instance'],
        'serverConfigId': value['serverConfigId'],
        'serverConfigName': value['serverConfigName'],
        'name': value['name'],
        'status': value['status'],
        'status_message': value['statusMessage'],
        'dns': value['dns'],
        'isBackupable': value['isBackupable'],
        'isRestorable': value['isRestorable'],
        'isPending': value['isPending'],
        'isNotFound': value['isNotFound'],
        'isHealthy': value['isHealthy'],
        'isStopped': value['isStopped'],
        'maintenance': value['maintenance'],
        'ports': ((value['ports'] as Array<any>).map(PortToJSON)),
        'env': (mapValues(value['env'], EnvironmentVariableToJSON)),
        'restartPolicy': RestartPolicyToJSON(value['restartPolicy']),
        'node': NodeToJSON(value['node']),
        'location': LocationToJSON(value['location']),
        'resources': ResourcePackageToJSON(value['resources']),
        'backups': ((value['backups'] as Array<any>).map(BackupToJSON)),
        'autoscaling': DockerServiceAutoscalingToJSON(value['autoscaling']),
        'metadata': value['metadata'],
        'createdAt': value['createdAt'] == null ? value['createdAt'] : value['createdAt'].toISOString(),
        'updatedAt': value['updatedAt'] == null ? value['updatedAt'] : value['updatedAt'].toISOString(),
    };
}

