/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceLogs
 */
export interface ServiceLogs {
    /**
     * The logs as an array of strings
     * @type {Array<string>}
     * @memberof ServiceLogs
     */
    logs: Array<string>;
}

/**
 * Check if a given object implements the ServiceLogs interface.
 */
export function instanceOfServiceLogs(value: object): value is ServiceLogs {
    if (!('logs' in value) || value['logs'] === undefined) return false;
    return true;
}

export function ServiceLogsFromJSON(json: any): ServiceLogs {
    return ServiceLogsFromJSONTyped(json, false);
}

export function ServiceLogsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceLogs {
    if (json == null) {
        return json;
    }
    return {
        
        'logs': json['logs'],
    };
}

export function ServiceLogsToJSON(json: any): ServiceLogs {
    return ServiceLogsToJSONTyped(json, false);
}

export function ServiceLogsToJSONTyped(value?: ServiceLogs | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logs': value['logs'],
    };
}

