/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ServerConfigStatus = {
    Pending: 'pending',
    Creating: 'creating',
    Updating: 'updating',
    Deleting: 'deleting',
    Waiting: 'waiting',
    Error: 'error',
    Ready: 'ready'
} as const;
export type ServerConfigStatus = typeof ServerConfigStatus[keyof typeof ServerConfigStatus];


export function instanceOfServerConfigStatus(value: any): boolean {
    for (const key in ServerConfigStatus) {
        if (Object.prototype.hasOwnProperty.call(ServerConfigStatus, key)) {
            if (ServerConfigStatus[key as keyof typeof ServerConfigStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServerConfigStatusFromJSON(json: any): ServerConfigStatus {
    return ServerConfigStatusFromJSONTyped(json, false);
}

export function ServerConfigStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerConfigStatus {
    return json as ServerConfigStatus;
}

export function ServerConfigStatusToJSON(value?: ServerConfigStatus | null): any {
    return value as any;
}

export function ServerConfigStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ServerConfigStatus {
    return value as ServerConfigStatus;
}

