/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetMetadataRequest
 */
export interface SetMetadataRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SetMetadataRequest
     */
    metadata?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SetMetadataRequest interface.
 */
export function instanceOfSetMetadataRequest(value: object): value is SetMetadataRequest {
    return true;
}

export function SetMetadataRequestFromJSON(json: any): SetMetadataRequest {
    return SetMetadataRequestFromJSONTyped(json, false);
}

export function SetMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function SetMetadataRequestToJSON(json: any): SetMetadataRequest {
    return SetMetadataRequestToJSONTyped(json, false);
}

export function SetMetadataRequestToJSONTyped(value?: SetMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': value['metadata'],
    };
}

