/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SteamRuntime } from './SteamRuntime';
import {
    SteamRuntimeFromJSON,
    SteamRuntimeFromJSONTyped,
    SteamRuntimeToJSON,
    SteamRuntimeToJSONTyped,
} from './SteamRuntime';

/**
 * 
 * @export
 * @interface Steam
 */
export interface Steam {
    /**
     * The Steam App ID
     * @type {number}
     * @memberof Steam
     */
    steamAppId: number;
    /**
     * The branch to use
     * @type {string}
     * @memberof Steam
     */
    branch: string;
    /**
     * The password to use
     * @type {string}
     * @memberof Steam
     */
    password: string | null;
    /**
     * The command to execute
     * @type {string}
     * @memberof Steam
     */
    command: string;
    /**
     * The steam account username
     * @type {string}
     * @memberof Steam
     */
    steamcmdUsername: string | null;
    /**
     * The steam account password
     * @type {string}
     * @memberof Steam
     */
    steamcmdPassword: string | null;
    /**
     * Whether or not the binary needs a graphical interface
     * @type {boolean}
     * @memberof Steam
     */
    headful: boolean;
    /**
     * Whether or not the the license agreement needs to be requested
     * @type {boolean}
     * @memberof Steam
     */
    requestLicense: boolean;
    /**
     * The steam runtime the server depends on
     * @type {SteamRuntime}
     * @memberof Steam
     */
    runtime: SteamRuntime;
    /**
     * A space-separated list of additional packages to install
     * @type {string}
     * @memberof Steam
     */
    additionalPackages: string | null;
    /**
     * Whether or not the steamworks app is unpublished or published
     * @type {boolean}
     * @memberof Steam
     */
    unpublished: boolean;
    /**
     * Indicates whether the steam binary is currently in use
     * @type {boolean}
     * @memberof Steam
     */
    inUse: boolean;
}



/**
 * Check if a given object implements the Steam interface.
 */
export function instanceOfSteam(value: object): value is Steam {
    if (!('steamAppId' in value) || value['steamAppId'] === undefined) return false;
    if (!('branch' in value) || value['branch'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    if (!('steamcmdUsername' in value) || value['steamcmdUsername'] === undefined) return false;
    if (!('steamcmdPassword' in value) || value['steamcmdPassword'] === undefined) return false;
    if (!('headful' in value) || value['headful'] === undefined) return false;
    if (!('requestLicense' in value) || value['requestLicense'] === undefined) return false;
    if (!('runtime' in value) || value['runtime'] === undefined) return false;
    if (!('additionalPackages' in value) || value['additionalPackages'] === undefined) return false;
    if (!('unpublished' in value) || value['unpublished'] === undefined) return false;
    if (!('inUse' in value) || value['inUse'] === undefined) return false;
    return true;
}

export function SteamFromJSON(json: any): Steam {
    return SteamFromJSONTyped(json, false);
}

export function SteamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Steam {
    if (json == null) {
        return json;
    }
    return {
        
        'steamAppId': json['steamAppId'],
        'branch': json['branch'],
        'password': json['password'],
        'command': json['command'],
        'steamcmdUsername': json['steamcmdUsername'],
        'steamcmdPassword': json['steamcmdPassword'],
        'headful': json['headful'],
        'requestLicense': json['requestLicense'],
        'runtime': SteamRuntimeFromJSON(json['runtime']),
        'additionalPackages': json['additionalPackages'],
        'unpublished': json['unpublished'],
        'inUse': json['inUse'],
    };
}

export function SteamToJSON(json: any): Steam {
    return SteamToJSONTyped(json, false);
}

export function SteamToJSONTyped(value?: Steam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steamAppId': value['steamAppId'],
        'branch': value['branch'],
        'password': value['password'],
        'command': value['command'],
        'steamcmdUsername': value['steamcmdUsername'],
        'steamcmdPassword': value['steamcmdPassword'],
        'headful': value['headful'],
        'requestLicense': value['requestLicense'],
        'runtime': SteamRuntimeToJSON(value['runtime']),
        'additionalPackages': value['additionalPackages'],
        'unpublished': value['unpublished'],
        'inUse': value['inUse'],
    };
}

