/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SteamRuntime = {
    Scout: 'scout',
    Soldier: 'soldier',
    Sniper: 'sniper',
    Steamrt4: 'steamrt4'
} as const;
export type SteamRuntime = typeof SteamRuntime[keyof typeof SteamRuntime];


export function instanceOfSteamRuntime(value: any): boolean {
    for (const key in SteamRuntime) {
        if (Object.prototype.hasOwnProperty.call(SteamRuntime, key)) {
            if (SteamRuntime[key as keyof typeof SteamRuntime] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SteamRuntimeFromJSON(json: any): SteamRuntime {
    return SteamRuntimeFromJSONTyped(json, false);
}

export function SteamRuntimeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SteamRuntime {
    return json as SteamRuntime;
}

export function SteamRuntimeToJSON(value?: SteamRuntime | null): any {
    return value as any;
}

export function SteamRuntimeToJSONTyped(value: any, ignoreDiscriminator: boolean): SteamRuntime {
    return value as SteamRuntime;
}

