/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StoreAppRequest
 */
export interface StoreAppRequest {
    /**
     * The name of the app
     * @type {string}
     * @memberof StoreAppRequest
     */
    name: string;
}

/**
 * Check if a given object implements the StoreAppRequest interface.
 */
export function instanceOfStoreAppRequest(value: object): value is StoreAppRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function StoreAppRequestFromJSON(json: any): StoreAppRequest {
    return StoreAppRequestFromJSONTyped(json, false);
}

export function StoreAppRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreAppRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function StoreAppRequestToJSON(json: any): StoreAppRequest {
    return StoreAppRequestToJSONTyped(json, false);
}

export function StoreAppRequestToJSONTyped(value?: StoreAppRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

