/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateUpdateSteam } from './CreateUpdateSteam';
import {
    CreateUpdateSteamFromJSON,
    CreateUpdateSteamFromJSONTyped,
    CreateUpdateSteamToJSON,
    CreateUpdateSteamToJSONTyped,
} from './CreateUpdateSteam';
import type { OperatingSystem } from './OperatingSystem';
import {
    OperatingSystemFromJSON,
    OperatingSystemFromJSONTyped,
    OperatingSystemToJSON,
    OperatingSystemToJSONTyped,
} from './OperatingSystem';
import type { BinaryType } from './BinaryType';
import {
    BinaryTypeFromJSON,
    BinaryTypeFromJSONTyped,
    BinaryTypeToJSON,
    BinaryTypeToJSONTyped,
} from './BinaryType';
import type { CreateUpdateDockerImage } from './CreateUpdateDockerImage';
import {
    CreateUpdateDockerImageFromJSON,
    CreateUpdateDockerImageFromJSONTyped,
    CreateUpdateDockerImageToJSON,
    CreateUpdateDockerImageToJSONTyped,
} from './CreateUpdateDockerImage';

/**
 * 
 * @export
 * @interface StoreBinaryRequest
 */
export interface StoreBinaryRequest {
    /**
     * The name of the binary
     * @type {string}
     * @memberof StoreBinaryRequest
     */
    name: string;
    /**
     * The version of the binary
     * @type {string}
     * @memberof StoreBinaryRequest
     */
    version: string;
    /**
     * The type of the binary
     * @type {BinaryType}
     * @memberof StoreBinaryRequest
     */
    type: BinaryType;
    /**
     * The operating system of the binary
     * @type {OperatingSystem}
     * @memberof StoreBinaryRequest
     */
    os: OperatingSystem;
    /**
     * The steam settings
     * @type {CreateUpdateSteam}
     * @memberof StoreBinaryRequest
     */
    steam?: CreateUpdateSteam;
    /**
     * The docker image settings
     * @type {CreateUpdateDockerImage}
     * @memberof StoreBinaryRequest
     */
    dockerImage?: CreateUpdateDockerImage;
}



/**
 * Check if a given object implements the StoreBinaryRequest interface.
 */
export function instanceOfStoreBinaryRequest(value: object): value is StoreBinaryRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('os' in value) || value['os'] === undefined) return false;
    return true;
}

export function StoreBinaryRequestFromJSON(json: any): StoreBinaryRequest {
    return StoreBinaryRequestFromJSONTyped(json, false);
}

export function StoreBinaryRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StoreBinaryRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'version': json['version'],
        'type': BinaryTypeFromJSON(json['type']),
        'os': OperatingSystemFromJSON(json['os']),
        'steam': json['steam'] == null ? undefined : CreateUpdateSteamFromJSON(json['steam']),
        'dockerImage': json['dockerImage'] == null ? undefined : CreateUpdateDockerImageFromJSON(json['dockerImage']),
    };
}

export function StoreBinaryRequestToJSON(json: any): StoreBinaryRequest {
    return StoreBinaryRequestToJSONTyped(json, false);
}

export function StoreBinaryRequestToJSONTyped(value?: StoreBinaryRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'version': value['version'],
        'type': BinaryTypeToJSON(value['type']),
        'os': OperatingSystemToJSON(value['os']),
        'steam': CreateUpdateSteamToJSON(value['steam']),
        'dockerImage': CreateUpdateDockerImageToJSON(value['dockerImage']),
    };
}

