/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TaggedImageMetaData
 */
export interface TaggedImageMetaData {
    /**
     * Whether the data was retrieved from the cache.
     * @type {boolean}
     * @memberof TaggedImageMetaData
     */
    cached: boolean;
    /**
     * Timestamp of when the data was last cached.
     * @type {string}
     * @memberof TaggedImageMetaData
     */
    cachedAt: string | null;
}

/**
 * Check if a given object implements the TaggedImageMetaData interface.
 */
export function instanceOfTaggedImageMetaData(value: object): value is TaggedImageMetaData {
    if (!('cached' in value) || value['cached'] === undefined) return false;
    if (!('cachedAt' in value) || value['cachedAt'] === undefined) return false;
    return true;
}

export function TaggedImageMetaDataFromJSON(json: any): TaggedImageMetaData {
    return TaggedImageMetaDataFromJSONTyped(json, false);
}

export function TaggedImageMetaDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): TaggedImageMetaData {
    if (json == null) {
        return json;
    }
    return {
        
        'cached': json['cached'],
        'cachedAt': json['cached_at'],
    };
}

export function TaggedImageMetaDataToJSON(json: any): TaggedImageMetaData {
    return TaggedImageMetaDataToJSONTyped(json, false);
}

export function TaggedImageMetaDataToJSONTyped(value?: TaggedImageMetaData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cached': value['cached'],
        'cached_at': value['cachedAt'],
    };
}

