/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateAppLocationSetting402Response
 */
export interface UpdateAppLocationSetting402Response {
    /**
     * 
     * @type {string}
     * @memberof UpdateAppLocationSetting402Response
     */
    message: string;
}

/**
 * Check if a given object implements the UpdateAppLocationSetting402Response interface.
 */
export function instanceOfUpdateAppLocationSetting402Response(value: object): value is UpdateAppLocationSetting402Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UpdateAppLocationSetting402ResponseFromJSON(json: any): UpdateAppLocationSetting402Response {
    return UpdateAppLocationSetting402ResponseFromJSONTyped(json, false);
}

export function UpdateAppLocationSetting402ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAppLocationSetting402Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function UpdateAppLocationSetting402ResponseToJSON(json: any): UpdateAppLocationSetting402Response {
    return UpdateAppLocationSetting402ResponseToJSONTyped(json, false);
}

export function UpdateAppLocationSetting402ResponseToJSONTyped(value?: UpdateAppLocationSetting402Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

