/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PortDefinition } from './PortDefinition';
import {
    PortDefinitionFromJSON,
    PortDefinitionFromJSONTyped,
    PortDefinitionToJSON,
    PortDefinitionToJSONTyped,
} from './PortDefinition';
import type { ConfigFile } from './ConfigFile';
import {
    ConfigFileFromJSON,
    ConfigFileFromJSONTyped,
    ConfigFileToJSON,
    ConfigFileToJSONTyped,
} from './ConfigFile';
import type { Mount } from './Mount';
import {
    MountFromJSON,
    MountFromJSONTyped,
    MountToJSON,
    MountToJSONTyped,
} from './Mount';
import type { RestartPolicy } from './RestartPolicy';
import {
    RestartPolicyFromJSON,
    RestartPolicyFromJSONTyped,
    RestartPolicyToJSON,
    RestartPolicyToJSONTyped,
} from './RestartPolicy';
import type { SecretFile } from './SecretFile';
import {
    SecretFileFromJSON,
    SecretFileFromJSONTyped,
    SecretFileToJSON,
    SecretFileToJSONTyped,
} from './SecretFile';
import type { EnvironmentVariableDefinition } from './EnvironmentVariableDefinition';
import {
    EnvironmentVariableDefinitionFromJSON,
    EnvironmentVariableDefinitionFromJSONTyped,
    EnvironmentVariableDefinitionToJSON,
    EnvironmentVariableDefinitionToJSONTyped,
} from './EnvironmentVariableDefinition';

/**
 * 
 * @export
 * @interface UpdateServerConfigRequest
 */
export interface UpdateServerConfigRequest {
    /**
     * The name of the server configuration
     * @type {string}
     * @memberof UpdateServerConfigRequest
     */
    name: string;
    /**
     * The arguments to pass to the command (overrides CMD of the Dockerfile)
     * @type {string}
     * @memberof UpdateServerConfigRequest
     */
    args?: string | null;
    /**
     * The command to run in the container (overrides ENTRYPOINT of the Dockerfile)
     * @type {string}
     * @memberof UpdateServerConfigRequest
     */
    command?: string | null;
    /**
     * The notes of the server config - to keep track of things and to inform colleagues
     * @type {string}
     * @memberof UpdateServerConfigRequest
     */
    notes?: string | null;
    /**
     * The binary id of the server configuration
     * @type {number}
     * @memberof UpdateServerConfigRequest
     */
    binaryId: number;
    /**
     * The slug of the resource package
     * @type {string}
     * @memberof UpdateServerConfigRequest
     */
    resourcePackageSlug: string;
    /**
     * The config files used in this server configuration
     * @type {Array<ConfigFile>}
     * @memberof UpdateServerConfigRequest
     */
    configFiles?: Array<ConfigFile>;
    /**
     * The secret files used in this server configuration
     * @type {Array<SecretFile>}
     * @memberof UpdateServerConfigRequest
     */
    secretFiles?: Array<SecretFile>;
    /**
     * The restart policy of the server configuration
     * @type {RestartPolicy}
     * @memberof UpdateServerConfigRequest
     */
    restartPolicy?: RestartPolicy;
    /**
     * The environment variables used in this server configuration
     * @type {Array<EnvironmentVariableDefinition>}
     * @memberof UpdateServerConfigRequest
     */
    env?: Array<EnvironmentVariableDefinition>;
    /**
     * The mounts used in this server configuration
     * @type {Array<Mount>}
     * @memberof UpdateServerConfigRequest
     */
    mounts?: Array<Mount>;
    /**
     * The port definitions
     * @type {Array<PortDefinition>}
     * @memberof UpdateServerConfigRequest
     */
    ports?: Array<PortDefinition>;
}

/**
 * Check if a given object implements the UpdateServerConfigRequest interface.
 */
export function instanceOfUpdateServerConfigRequest(value: object): value is UpdateServerConfigRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('binaryId' in value) || value['binaryId'] === undefined) return false;
    if (!('resourcePackageSlug' in value) || value['resourcePackageSlug'] === undefined) return false;
    return true;
}

export function UpdateServerConfigRequestFromJSON(json: any): UpdateServerConfigRequest {
    return UpdateServerConfigRequestFromJSONTyped(json, false);
}

export function UpdateServerConfigRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateServerConfigRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'args': json['args'] == null ? undefined : json['args'],
        'command': json['command'] == null ? undefined : json['command'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'binaryId': json['binaryId'],
        'resourcePackageSlug': json['resourcePackageSlug'],
        'configFiles': json['configFiles'] == null ? undefined : ((json['configFiles'] as Array<any>).map(ConfigFileFromJSON)),
        'secretFiles': json['secretFiles'] == null ? undefined : ((json['secretFiles'] as Array<any>).map(SecretFileFromJSON)),
        'restartPolicy': json['restartPolicy'] == null ? undefined : RestartPolicyFromJSON(json['restartPolicy']),
        'env': json['env'] == null ? undefined : ((json['env'] as Array<any>).map(EnvironmentVariableDefinitionFromJSON)),
        'mounts': json['mounts'] == null ? undefined : ((json['mounts'] as Array<any>).map(MountFromJSON)),
        'ports': json['ports'] == null ? undefined : ((json['ports'] as Array<any>).map(PortDefinitionFromJSON)),
    };
}

export function UpdateServerConfigRequestToJSON(json: any): UpdateServerConfigRequest {
    return UpdateServerConfigRequestToJSONTyped(json, false);
}

export function UpdateServerConfigRequestToJSONTyped(value?: UpdateServerConfigRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'args': value['args'],
        'command': value['command'],
        'notes': value['notes'],
        'binaryId': value['binaryId'],
        'resourcePackageSlug': value['resourcePackageSlug'],
        'configFiles': value['configFiles'] == null ? undefined : ((value['configFiles'] as Array<any>).map(ConfigFileToJSON)),
        'secretFiles': value['secretFiles'] == null ? undefined : ((value['secretFiles'] as Array<any>).map(SecretFileToJSON)),
        'restartPolicy': RestartPolicyToJSON(value['restartPolicy']),
        'env': value['env'] == null ? undefined : ((value['env'] as Array<any>).map(EnvironmentVariableDefinitionToJSON)),
        'mounts': value['mounts'] == null ? undefined : ((value['mounts'] as Array<any>).map(MountToJSON)),
        'ports': value['ports'] == null ? undefined : ((value['ports'] as Array<any>).map(PortDefinitionToJSON)),
    };
}

