"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      Alternatively, you can copy your API key directly from our **[`console`](https://console.4players.io)** by opening any app, and then going to **Settings -> API Keys**.
 *
 * The version of the OpenAPI document: 0.9.3
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.DockerRegistryApi = void 0;
const runtime = __importStar(require("../runtime"));
const index_1 = require("../models/index");
/**
 *
 */
class DockerRegistryApi extends runtime.BaseAPI {
    /**
     * Create a new docker registry
     */
    async createDockerRegistryRaw(requestParameters, initOverrides) {
        if (requestParameters['storeDockerRegistryRequest'] == null) {
            throw new runtime.RequiredError('storeDockerRegistryRequest', 'Required parameter "storeDockerRegistryRequest" was null or undefined when calling createDockerRegistry().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/v1/docker-registries`;
        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.StoreDockerRegistryRequestToJSON)(requestParameters['storeDockerRegistryRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.DockerRegistryFromJSON)(jsonValue));
    }
    /**
     * Create a new docker registry
     */
    async createDockerRegistry(requestParameters, initOverrides) {
        const response = await this.createDockerRegistryRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Delete a specific docker registry
     */
    async deleteDockerRegistryRaw(requestParameters, initOverrides) {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError('dockerRegistry', 'Required parameter "dockerRegistry" was null or undefined when calling deleteDockerRegistry().');
        }
        const queryParameters = {};
        const headerParameters = {};
        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));
        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.VoidApiResponse(response);
    }
    /**
     * Delete a specific docker registry
     */
    async deleteDockerRegistry(requestParameters, initOverrides) {
        await this.deleteDockerRegistryRaw(requestParameters, initOverrides);
    }
    /**
     * Show all docker registries
     */
    async getDockerRegistriesRaw(requestParameters, initOverrides) {
        const queryParameters = {};
        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }
        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }
        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }
        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }
        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }
        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }
        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }
        if (requestParameters['filterUrl'] != null) {
            queryParameters['filter[url]'] = requestParameters['filterUrl'];
        }
        if (requestParameters['filterOrganization'] != null) {
            queryParameters['filter[organization]'] = requestParameters['filterOrganization'];
        }
        const headerParameters = {};
        let urlPath = `/v1/docker-registries`;
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.GetDockerRegistries200ResponseFromJSON)(jsonValue));
    }
    /**
     * Show all docker registries
     */
    async getDockerRegistries(requestParameters = {}, initOverrides) {
        const response = await this.getDockerRegistriesRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Display a specific docker registry
     */
    async getDockerRegistryByIdRaw(requestParameters, initOverrides) {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError('dockerRegistry', 'Required parameter "dockerRegistry" was null or undefined when calling getDockerRegistryById().');
        }
        const queryParameters = {};
        const headerParameters = {};
        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.DockerRegistryFromJSON)(jsonValue));
    }
    /**
     * Display a specific docker registry
     */
    async getDockerRegistryById(requestParameters, initOverrides) {
        const response = await this.getDockerRegistryByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * List all available tagged images
     */
    async getTaggedImagesRaw(requestParameters, initOverrides) {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError('dockerRegistry', 'Required parameter "dockerRegistry" was null or undefined when calling getTaggedImages().');
        }
        const queryParameters = {};
        const headerParameters = {};
        let urlPath = `/v1/docker-registries/{dockerRegistry}/tagged-images`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.GetTaggedImages200ResponseFromJSON)(jsonValue));
    }
    /**
     * List all available tagged images
     */
    async getTaggedImages(requestParameters, initOverrides) {
        const response = await this.getTaggedImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Refresh the cache for all available tagged images
     */
    async refreshTaggedImagesRaw(requestParameters, initOverrides) {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError('dockerRegistry', 'Required parameter "dockerRegistry" was null or undefined when calling refreshTaggedImages().');
        }
        const queryParameters = {};
        const headerParameters = {};
        let urlPath = `/v1/docker-registries/{dockerRegistry}/tagged-images/refresh`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.GetTaggedImages200ResponseFromJSON)(jsonValue));
    }
    /**
     * Refresh the cache for all available tagged images
     */
    async refreshTaggedImages(requestParameters, initOverrides) {
        const response = await this.refreshTaggedImagesRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Update a specific docker registry
     */
    async updateDockerRegistryRaw(requestParameters, initOverrides) {
        if (requestParameters['dockerRegistry'] == null) {
            throw new runtime.RequiredError('dockerRegistry', 'Required parameter "dockerRegistry" was null or undefined when calling updateDockerRegistry().');
        }
        if (requestParameters['updateDockerRegistryRequest'] == null) {
            throw new runtime.RequiredError('updateDockerRegistryRequest', 'Required parameter "updateDockerRegistryRequest" was null or undefined when calling updateDockerRegistry().');
        }
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/v1/docker-registries/{dockerRegistry}`;
        urlPath = urlPath.replace(`{${"dockerRegistry"}}`, encodeURIComponent(String(requestParameters['dockerRegistry'])));
        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.UpdateDockerRegistryRequestToJSON)(requestParameters['updateDockerRegistryRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.DockerRegistryFromJSON)(jsonValue));
    }
    /**
     * Update a specific docker registry
     */
    async updateDockerRegistry(requestParameters, initOverrides) {
        const response = await this.updateDockerRegistryRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.DockerRegistryApi = DockerRegistryApi;
