"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.GetResourcePackagesSortEnum = exports.ResourcePackageApi = void 0;
const runtime = __importStar(require("../runtime"));
const index_1 = require("../models/index");
/**
 *
 */
class ResourcePackageApi extends runtime.BaseAPI {
    /**
     * Show a specified resource package
     */
    async getResourcePackageByIdRaw(requestParameters, initOverrides) {
        if (requestParameters['resourcePackage'] == null) {
            throw new runtime.RequiredError('resourcePackage', 'Required parameter "resourcePackage" was null or undefined when calling getResourcePackageById().');
        }
        const queryParameters = {};
        const headerParameters = {};
        let urlPath = `/v1/resource-packages/{resourcePackage}`;
        urlPath = urlPath.replace(`{${"resourcePackage"}}`, encodeURIComponent(String(requestParameters['resourcePackage'])));
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.ResourcePackageFromJSON)(jsonValue));
    }
    /**
     * Show a specified resource package
     */
    async getResourcePackageById(requestParameters, initOverrides) {
        const response = await this.getResourcePackageByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Show all available resource packages
     */
    async getResourcePackagesRaw(requestParameters, initOverrides) {
        const queryParameters = {};
        if (requestParameters['perPage'] != null) {
            queryParameters['perPage'] = requestParameters['perPage'];
        }
        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }
        if (requestParameters['sort'] != null) {
            queryParameters['sort[]'] = requestParameters['sort'];
        }
        if (requestParameters['filterId'] != null) {
            queryParameters['filter[id]'] = requestParameters['filterId'];
        }
        if (requestParameters['filterName'] != null) {
            queryParameters['filter[name]'] = requestParameters['filterName'];
        }
        if (requestParameters['filterNamePartial'] != null) {
            queryParameters['filter[namePartial]'] = requestParameters['filterNamePartial'];
        }
        if (requestParameters['filterSlug'] != null) {
            queryParameters['filter[slug]'] = requestParameters['filterSlug'];
        }
        if (requestParameters['filterType'] != null) {
            queryParameters['filter[type]'] = requestParameters['filterType'];
        }
        if (requestParameters['filterCpuLimit'] != null) {
            queryParameters['filter[cpuLimit]'] = requestParameters['filterCpuLimit'];
        }
        if (requestParameters['filterMemoryLimitMiB'] != null) {
            queryParameters['filter[memoryLimitMiB]'] = requestParameters['filterMemoryLimitMiB'];
        }
        const headerParameters = {};
        let urlPath = `/v1/resource-packages`;
        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.GetResourcePackages200ResponseFromJSON)(jsonValue));
    }
    /**
     * Show all available resource packages
     */
    async getResourcePackages(requestParameters = {}, initOverrides) {
        const response = await this.getResourcePackagesRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.ResourcePackageApi = ResourcePackageApi;
/**
 * @export
 */
exports.GetResourcePackagesSortEnum = {
    Id: '-id',
    Id2: 'id',
    Name: '-name',
    Name2: 'name',
    Slug: '-slug',
    Slug2: 'slug',
    Type: '-type',
    Type2: 'type',
    CpuLimit: '-cpuLimit',
    CpuLimit2: 'cpuLimit',
    MemoryLimitMiB: '-memoryLimitMiB',
    MemoryLimitMiB2: 'memoryLimitMiB'
};
