"use strict";
/* tslint:disable */
/* eslint-disable */
/**
 * ODIN Fleet API
 * API to access Odin Fleet, empowering developers to deploy gameservers all around the world in just a few lines of code.  To authenticate, users must send their email, password, and session ID to the **[`/api/auth`](/operations/getAuthToken)** endpoint. Upon successful authentication, an API token will be provided. This token should be included in the `Authorization` header as a Bearer token for all subsequent requests.      The API token can also be retrieved manually via the Console Dashboard (https://console.4players.io) under **User Settings > Tokens**.
 *
 * The version of the OpenAPI document: 0.9.4
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.TemplateAppApi = void 0;
const runtime = __importStar(require("../runtime"));
const index_1 = require("../models/index");
/**
 *
 */
class TemplateAppApi extends runtime.BaseAPI {
    /**
     * Create a Minecraft template app
     */
    async createMinecraftTemplateRaw(requestParameters, initOverrides) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/v1/templates/apps/minecraft`;
        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.StoreMinecraftTemplateRequestToJSON)(requestParameters['storeMinecraftTemplateRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.AppFromJSON)(jsonValue));
    }
    /**
     * Create a Minecraft template app
     */
    async createMinecraftTemplate(requestParameters = {}, initOverrides) {
        const response = await this.createMinecraftTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Create an OpenClaw template app
     */
    async createOpenClawTemplateRaw(requestParameters, initOverrides) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/v1/templates/apps/openclaw`;
        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.StoreOpenClawTemplateRequestToJSON)(requestParameters['storeOpenClawTemplateRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.TemplateAppResultFromJSON)(jsonValue));
    }
    /**
     * Create an OpenClaw template app
     */
    async createOpenClawTemplate(requestParameters = {}, initOverrides) {
        const response = await this.createOpenClawTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }
    /**
     * Create a Palworld template app
     */
    async createPalworldTemplateRaw(requestParameters, initOverrides) {
        const queryParameters = {};
        const headerParameters = {};
        headerParameters['Content-Type'] = 'application/json';
        let urlPath = `/v1/templates/apps/palworld`;
        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: (0, index_1.StorePalworldTemplateRequestToJSON)(requestParameters['storePalworldTemplateRequest']),
        }, initOverrides);
        return new runtime.JSONApiResponse(response, (jsonValue) => (0, index_1.AppFromJSON)(jsonValue));
    }
    /**
     * Create a Palworld template app
     */
    async createPalworldTemplate(requestParameters = {}, initOverrides) {
        const response = await this.createPalworldTemplateRaw(requestParameters, initOverrides);
        return await response.value();
    }
}
exports.TemplateAppApi = TemplateAppApi;
